export interface ExerciseStep {
  instruction: string;
  duration: number;
}

export interface Exercise {
  id: string;
  title: string;
  subtitle: string;
  category: ExerciseCategory;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  durationMinutes: number;
  benefits: string[];
  steps: ExerciseStep[];
  iconName: string;
  targetConditions: TargetCondition[];
  scienceNote: string;
  preparationTips: string[];
  expectedSensations: string[];
  contraindications: string[];
  researchCitation: string;
  methodology: 'MABT' | 'exposure' | 'mindfulness' | 'somatic' | 'breathwork';
  framework: string;
}

export type ExerciseCategory = 'heartbeat' | 'breathing' | 'bodyScanning' | 'tension' | 'temperature' | 'exposure' | 'gut' | 'movement';
export type TargetCondition = 'anxiety' | 'ptsd' | 'panic' | 'depression' | 'eating-disorders' | 'chronic-pain' | 'alexithymia' | 'general' | 'sleep' | 'stress';

export const CATEGORY_INFO: Record<ExerciseCategory, { label: string; icon: string; description: string; color: string }> = {
  heartbeat: { label: 'Heartbeat', icon: 'heart', description: 'Detect and attune to your cardiac rhythm', color: '#E85D5D' },
  breathing: { label: 'Breathwork', icon: 'wind', description: 'Master breath awareness and autonomic control', color: '#88B3B5' },
  bodyScanning: { label: 'Body Scan', icon: 'activity', description: 'Systematically map internal sensations', color: '#6B5B95' },
  tension: { label: 'Tension', icon: 'zap', description: 'Locate and release muscular holding patterns', color: '#F0C05A' },
  temperature: { label: 'Temperature', icon: 'thermometer', description: 'Develop thermal interoceptive precision', color: '#E8B4B8' },
  exposure: { label: 'Exposure', icon: 'shield', description: 'Build distress tolerance through safe exposure', color: '#7FB069' },
  gut: { label: 'Gut Signals', icon: 'circle', description: 'Connect with your enteric nervous system', color: '#C4A484' },
  movement: { label: 'Movement', icon: 'move', description: 'Proprioceptive awareness through mindful motion', color: '#6AABCF' },
};

export const EXERCISES: Exercise[] = [
  {
    id: 'heartbeat-detection',
    title: 'Heartbeat Detection',
    subtitle: 'Feel your pulse without touching',
    category: 'heartbeat',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Improves cardiac interoceptive accuracy', 'Reduces anxiety sensitivity by 23% (Garfinkel et al., 2015)', 'Grounds attention in present-moment body signals', 'Builds foundation for emotional awareness'],
    iconName: 'heart',
    targetConditions: ['anxiety', 'panic', 'general', 'alexithymia'],
    scienceNote: 'Heartbeat detection tasks are the gold standard in interoception research. The insular cortex processes cardiac signals, and training this pathway strengthens the neural bridge between body and conscious awareness.',
    preparationTips: ['Find a quiet space free from distractions', 'Sit or lie in a comfortable position', 'Avoid caffeine 30 minutes before practice', 'Loosen any tight clothing around your chest'],
    expectedSensations: ['Subtle pulsing in chest or throat', 'Tingling in fingertips', 'Warmth spreading through limbs', 'Heightened awareness of breathing'],
    contraindications: ['Severe cardiac anxiety - start with breathing exercises first', 'Recent cardiac event - consult physician'],
    researchCitation: 'Garfinkel et al. (2015). Knowing your own heart: Distinguishing interoceptive accuracy from interoceptive sensibility. Biological Psychology, 104, 65-74.',
    methodology: 'MABT',
    framework: 'Notice: Detect heartbeat. Describe: Rate clarity 1-10. Connect: Link to emotional state.',
    steps: [
      { instruction: 'Find a comfortable seated position. Close your eyes gently and let your body settle.', duration: 15 },
      { instruction: 'Take three deep breaths to activate your parasympathetic system. Let your breathing return to its natural rhythm.', duration: 20 },
      { instruction: 'Without placing your hand on your chest, turn your attention inward. Can you sense your heartbeat from within?', duration: 30 },
      { instruction: 'Focus your attention on your chest area. Notice any rhythmic sensation, however faint. Stay curious.', duration: 45 },
      { instruction: 'If you can feel it, count the beats silently. If not, that is perfectly fine - awareness develops with practice.', duration: 45 },
      { instruction: 'Now shift attention to your fingertips. Can you feel a pulse there? The capillaries carry your heartbeat to your extremities.', duration: 30 },
      { instruction: 'Move your awareness to your neck. The carotid artery often provides a strong signal. Notice any pulsing.', duration: 30 },
      { instruction: 'Return attention to your chest. Notice if your awareness has sharpened. Your insula is building new neural pathways.', duration: 45 },
      { instruction: 'Gently open your eyes. Take a moment to reflect on what you noticed. Even partial awareness is meaningful progress.', duration: 20 },
    ],
  },
  {
    id: 'heartbeat-tracking',
    title: 'Heartbeat Tracking',
    subtitle: 'Deep cardiac interoception practice',
    category: 'heartbeat',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Deepens cardiac-brain connection', 'Calms autonomic nervous system', 'Enhances emotional granularity', 'Improves interoceptive accuracy scores'],
    iconName: 'heart',
    targetConditions: ['anxiety', 'panic', 'stress', 'general'],
    scienceNote: 'Research shows people with higher heartbeat detection accuracy have greater emotional awareness and better decision-making. The anterior insula integrates cardiac signals with emotional context.',
    preparationTips: ['Lie down for optimal detection', 'Practice after light exercise for stronger signal', 'Use a quiet room with minimal background noise'],
    expectedSensations: ['Rhythmic pulsing in chest', 'Heart rate changes with breath', 'Warmth in torso', 'Deep sense of internal rhythm'],
    contraindications: ['Active panic disorder - build up gradually', 'Heart arrhythmia awareness may increase anxiety temporarily'],
    researchCitation: 'Critchley et al. (2004). Neural systems supporting interoceptive awareness. Nature Neuroscience, 7(2), 189-195.',
    methodology: 'MABT',
    framework: 'Notice: Track heart rhythm shifts. Describe: Fast/slow/steady/irregular. Connect: How does rhythm relate to current emotional state?',
    steps: [
      { instruction: 'Lie down comfortably on your back. Let your arms rest by your sides, palms facing up.', duration: 20 },
      { instruction: 'Close your eyes. Begin with five slow, deep breaths. Each exhale activates your vagus nerve.', duration: 30 },
      { instruction: 'Let your breathing settle naturally. Turn your full attention inward to the center of your chest.', duration: 20 },
      { instruction: 'Focus on the center of your chest. Imagine listening with your whole body. Your insula is receiving cardiac signals right now.', duration: 40 },
      { instruction: 'Notice any rhythmic sensation, however faint. Stay curious, not forceful. Detection improves with patience.', duration: 60 },
      { instruction: 'If you notice your heartbeat, observe its rhythm. Is it fast? Slow? Steady? Irregular? Simply witness without judgment.', duration: 60 },
      { instruction: 'Now take a slightly deeper breath and hold for 3 seconds. Notice how your heart responds - it should briefly accelerate.', duration: 30 },
      { instruction: 'Release the breath slowly. Feel the heartbeat settle. This is respiratory sinus arrhythmia - proof of vagal tone.', duration: 30 },
      { instruction: 'Repeat: deeper breath, hold, release. Each time, observe your heart with increasing precision.', duration: 60 },
      { instruction: 'Rest in stillness. Simply witness your heart doing its work. It beats 100,000 times per day without your conscious effort.', duration: 60 },
      { instruction: 'Slowly bring awareness back to the room. Open your eyes when ready. Notice how connected you feel to your body.', duration: 20 },
    ],
  },
  {
    id: 'heartbeat-emotion',
    title: 'Heartbeat & Emotion Link',
    subtitle: 'Connect cardiac signals to feelings',
    category: 'heartbeat',
    difficulty: 'advanced',
    durationMinutes: 10,
    benefits: ['Develops emotional granularity through body signals', 'Strengthens insula-prefrontal cortex connection', 'Improves early emotional detection', 'Builds capacity for emotion regulation'],
    iconName: 'heart',
    targetConditions: ['alexithymia', 'depression', 'anxiety', 'eating-disorders'],
    scienceNote: 'The anterior insula integrates cardiac signals with emotional processing. People with alexithymia (difficulty identifying emotions) show reduced insula activation during heartbeat tasks. This exercise directly trains that pathway.',
    preparationTips: ['Review recent emotional experiences beforehand', 'Have a quiet, private space', 'Be prepared for emotions to surface - this is the exercise working'],
    expectedSensations: ['Heart rate changes with different emotions', 'Chest tightness or openness', 'Temperature shifts', 'Gut responses to emotional memories'],
    contraindications: ['Active trauma flashbacks - work with therapist', 'Severe dissociation - start with grounding exercises', 'Unprocessed grief - proceed gently'],
    researchCitation: 'Herbert et al. (2011). Interoception across modalities: On the relationship between cardiac awareness and the sensitivity for gastric functions. PLoS ONE, 6(11).',
    methodology: 'MABT',
    framework: 'Notice: Cardiac shift with emotion. Describe: Name the emotion and body change. Connect: What is your body telling you about this feeling?',
    steps: [
      { instruction: 'Sit comfortably. Close your eyes. Begin by finding your heartbeat - let your attention settle in your chest.', duration: 30 },
      { instruction: 'Spend a moment establishing your baseline. How fast is your heart? How strong is the signal? Rate clarity 1-10.', duration: 40 },
      { instruction: 'Now gently recall a moment of joy or gratitude. A genuine smile, a warm connection. Let the memory fill you.', duration: 30 },
      { instruction: 'Notice your heartbeat now. Has anything shifted? Rate, rhythm, strength? Where do you feel this emotion in your body?', duration: 40 },
      { instruction: 'Release the memory. Take three breaths to return to neutral. Let your heart settle.', duration: 25 },
      { instruction: 'Now recall a moment of mild stress or frustration. Nothing overwhelming - just mildly activating.', duration: 25 },
      { instruction: 'Notice your heartbeat. Has it quickened? Intensified? What other body signals accompany this emotion? Jaw? Shoulders? Stomach?', duration: 40 },
      { instruction: 'Release. Three breaths to neutral. You are safe. The stress was just a memory.', duration: 20 },
      { instruction: 'Recall a moment of calm confidence. Feeling capable and grounded. Where do you feel this in your body?', duration: 30 },
      { instruction: 'Notice your heartbeat with this emotion. Steady? Slow? Strong? This is what embodied confidence feels like.', duration: 40 },
      { instruction: 'Release all memories. Return to simply observing your heart in this present moment.', duration: 30 },
      { instruction: 'Reflect: each emotion had a different cardiac signature. Your heart speaks the language of emotions. Learning to listen is emotional intelligence.', duration: 30 },
      { instruction: 'Open your eyes. You have strengthened the bridge between your heart and your emotional awareness.', duration: 20 },
    ],
  },
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    subtitle: 'Navy SEAL 4-4-4-4 protocol',
    category: 'breathing',
    difficulty: 'beginner',
    durationMinutes: 6,
    benefits: ['Activates parasympathetic nervous system within 90 seconds', 'Reduces cortisol by up to 25%', 'Used by Navy SEALs for performance under pressure', 'Improves heart rate variability (HRV)'],
    iconName: 'wind',
    targetConditions: ['anxiety', 'panic', 'stress', 'ptsd', 'general'],
    scienceNote: 'Box breathing creates equal inhale-hold-exhale-hold cycles that balance sympathetic and parasympathetic nervous system activity. Research at Yale shows it improves HRV and emotional regulation within 5 minutes of practice.',
    preparationTips: ['Sit upright to maximize lung capacity', 'Breathe through your nose if possible', 'Start with 3-count if 4 feels too long'],
    expectedSensations: ['Gradual slowing of heart rate', 'Warmth spreading through limbs', 'Mental clarity and calm focus', 'Reduced muscle tension'],
    contraindications: ['Respiratory conditions - modify hold duration', 'Hyperventilation tendency - skip breath holds initially'],
    researchCitation: 'Ma et al. (2017). The effect of diaphragmatic breathing on attention, negative affect and stress in healthy adults. Frontiers in Psychology, 8, 874.',
    methodology: 'breathwork',
    framework: 'Notice: Breath rhythm. Describe: Chest expansion, air temperature. Connect: How does structured breathing shift your nervous system?',
    steps: [
      { instruction: 'Sit upright with your feet flat on the floor. Relax your shoulders away from your ears.', duration: 15 },
      { instruction: 'Exhale completely through your mouth, emptying your lungs fully. This resets your breathing cycle.', duration: 10 },
      { instruction: 'Inhale slowly through your nose for 4 counts. Feel your diaphragm expand.', duration: 6 },
      { instruction: 'Hold your breath for 4 counts. Stay relaxed - no tension in your face or shoulders.', duration: 6 },
      { instruction: 'Exhale slowly through your mouth for 4 counts. Control the release.', duration: 6 },
      { instruction: 'Hold empty for 4 counts. Embrace the stillness at the bottom of your breath.', duration: 6 },
      { instruction: 'Inhale through your nose for 4 counts. Feel your chest and belly expand together.', duration: 6 },
      { instruction: 'Hold for 4 counts. Notice the fullness. Your body is absorbing oxygen.', duration: 6 },
      { instruction: 'Exhale for 4 counts. Release all tension with the air.', duration: 6 },
      { instruction: 'Hold empty for 4 counts. Your parasympathetic system is activating now.', duration: 6 },
      { instruction: 'Continue this pattern. Inhale 4 counts.', duration: 6 },
      { instruction: 'Hold 4 counts.', duration: 6 },
      { instruction: 'Exhale 4 counts.', duration: 6 },
      { instruction: 'Hold empty 4 counts.', duration: 6 },
      { instruction: 'Two more rounds on your own. Maintain the rhythm. Notice how your body has shifted.', duration: 50 },
      { instruction: 'Let your breathing return to its natural rhythm. Notice the calm clarity. This is your parasympathetic system online.', duration: 20 },
    ],
  },
  {
    id: 'diaphragmatic-breathing',
    title: 'Diaphragmatic Breathing',
    subtitle: 'Deep belly breath for vagal activation',
    category: 'breathing',
    difficulty: 'beginner',
    durationMinutes: 7,
    benefits: ['Reduces heart rate by 10-15 BPM', 'Lowers systolic blood pressure 5-8 mmHg', 'Promotes deep vagal tone activation', 'Foundation for all breathwork practices'],
    iconName: 'wind',
    targetConditions: ['anxiety', 'panic', 'stress', 'chronic-pain', 'sleep', 'general'],
    scienceNote: 'Diaphragmatic breathing stimulates the vagus nerve through mechanical compression, activating the parasympathetic nervous system. 8 weeks of daily practice reduces sympathetic reactivity in PTSD patients (Hopper et al., 2019).',
    preparationTips: ['Place one hand on chest, one on belly to monitor', 'Lying down makes diaphragmatic engagement easier', 'The belly hand should rise more than the chest hand'],
    expectedSensations: ['Belly expansion on inhale', 'Gradual heart rate reduction', 'Warmth in extremities', 'Yawning (sign of parasympathetic activation)'],
    contraindications: ['None - safe for all populations', 'Modify if lying position is uncomfortable'],
    researchCitation: 'Hopper, S. I., et al. (2019). Effectiveness of diaphragmatic breathing for reducing physiological and psychological stress. Journal of Clinical Nursing, 28(3-4), 681-691.',
    methodology: 'breathwork',
    framework: 'Notice: Belly vs chest movement. Describe: Depth, ease, resistance. Connect: How does belly breathing change your internal state?',
    steps: [
      { instruction: 'Lie on your back or sit comfortably. Place one hand on your chest, one on your belly.', duration: 15 },
      { instruction: 'Breathe normally for a moment. Notice which hand rises more. Most stressed people breathe into their chest.', duration: 20 },
      { instruction: 'Now inhale slowly through your nose. Direct the breath deep into your belly.', duration: 10 },
      { instruction: 'Your belly hand should rise while your chest hand stays relatively still. This engages your diaphragm.', duration: 10 },
      { instruction: 'Exhale slowly through pursed lips. Feel your belly lower as the diaphragm relaxes upward.', duration: 10 },
      { instruction: 'Continue this pattern. Inhale into the belly for 4 counts. Your vagus nerve is being stimulated.', duration: 8 },
      { instruction: 'Exhale slowly for 6 counts. The longer exhale activates parasympathetic dominance.', duration: 10 },
      { instruction: 'Keep going. Inhale 4 counts into the belly. Feel the expansion.', duration: 8 },
      { instruction: 'Exhale 6 counts. Feel the relaxation deepening with each cycle.', duration: 10 },
      { instruction: 'Continue for several more breaths on your own. Find your natural rhythm within the 4:6 ratio.', duration: 90 },
      { instruction: 'Notice the quality of calm in your body now. Your cortisol levels have measurably decreased.', duration: 30 },
      { instruction: 'Release the technique. Breathe naturally. Notice how different your body feels compared to when you started.', duration: 20 },
    ],
  },
  {
    id: '478-breathing',
    title: '4-7-8 Relaxation Breath',
    subtitle: 'Dr. Weil\'s natural tranquilizer',
    category: 'breathing',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Induces deep parasympathetic activation', 'Clinically shown to improve sleep onset by 40%', 'Reduces acute anxiety within 4 breath cycles', 'Activates the vagus nerve through extended exhale'],
    iconName: 'wind',
    targetConditions: ['anxiety', 'sleep', 'panic', 'stress'],
    scienceNote: 'Developed by Dr. Andrew Weil based on pranayama principles. The extended 8-count exhale creates maximum vagal stimulation. The 7-count hold allows full oxygen absorption and CO2 exchange.',
    preparationTips: ['Touch tongue to ridge behind upper front teeth throughout', 'Exhale through mouth with a whoosh sound', 'Start with 4 cycles, build to 8'],
    expectedSensations: ['Deep drowsiness after 4+ cycles', 'Lightheadedness initially (normal)', 'Progressive muscle relaxation', 'Slowed thought patterns'],
    contraindications: ['Respiratory conditions - reduce hold to 4 counts', 'Pregnancy - consult physician for breath holds'],
    researchCitation: 'Weil, A. (2015). Breathing: The Master Key to Self-Healing. Sounds True Publishing.',
    methodology: 'breathwork',
    framework: 'Notice: Depth of calm after each cycle. Describe: Physical changes cycle-by-cycle. Connect: At what point does your nervous system shift?',
    steps: [
      { instruction: 'Sit comfortably with your back straight. Let your tongue rest behind your upper front teeth throughout.', duration: 15 },
      { instruction: 'Exhale completely through your mouth, making a whoosh sound. Empty fully.', duration: 10 },
      { instruction: 'Close your mouth. Inhale quietly through your nose for 4 counts.', duration: 8 },
      { instruction: 'Hold your breath for 7 counts. Stay relaxed - this allows full oxygen absorption.', duration: 10 },
      { instruction: 'Exhale completely through your mouth with a whoosh for 8 counts. This long exhale maximizes vagal activation.', duration: 12 },
      { instruction: 'That completes one cycle. Inhale again for 4 counts through your nose.', duration: 8 },
      { instruction: 'Hold for 7 counts. Notice the stillness within. Your body is recalibrating.', duration: 10 },
      { instruction: 'Exhale with whoosh for 8 counts. Feel tension leaving your muscles.', duration: 12 },
      { instruction: 'Third cycle. Inhale 4 counts.', duration: 8 },
      { instruction: 'Hold 7 counts. Your parasympathetic system is now dominant.', duration: 10 },
      { instruction: 'Exhale 8 counts. Deeply releasing with each breath.', duration: 12 },
      { instruction: 'Fourth cycle. Inhale 4 counts.', duration: 8 },
      { instruction: 'Hold 7 counts. You may notice a profound sense of peace settling in.', duration: 10 },
      { instruction: 'Exhale 8 counts. Complete release. Your body knows what to do.', duration: 12 },
      { instruction: 'Continue for 3 more rounds at your own pace. Dr. Weil recommends no more than 8 cycles per session.', duration: 100 },
      { instruction: 'Return to natural breathing. Notice the profound calm. This technique gets more powerful with daily practice.', duration: 30 },
    ],
  },
  {
    id: 'breath-temperature',
    title: 'Breath Temperature Sensing',
    subtitle: 'Detect thermal shifts in your breath',
    category: 'breathing',
    difficulty: 'intermediate',
    durationMinutes: 6,
    benefits: ['Develops fine-grained interoceptive sensitivity', 'Anchors attention through subtle sensation', 'Reduces rumination by engaging sensory focus', 'Trains discriminative awareness'],
    iconName: 'wind',
    targetConditions: ['anxiety', 'stress', 'alexithymia', 'general'],
    scienceNote: 'Temperature-based breath awareness engages the trigeminal nerve endings in the nostrils, providing a strong interoceptive anchor. This is a core technique in MABT for developing sensory discrimination.',
    preparationTips: ['Breathe exclusively through your nose', 'A slightly cool room makes contrast more noticeable', 'Close your eyes for enhanced sensitivity'],
    expectedSensations: ['Cool air entering nostrils', 'Warm air exiting', 'Increased nasal sensitivity', 'Subtle temperature gradients along airways'],
    contraindications: ['Nasal congestion may limit effectiveness'],
    researchCitation: 'Price & Hooven (2018). Interoceptive awareness skills for emotion regulation. Frontiers in Psychology, 9, 798.',
    methodology: 'MABT',
    framework: 'Notice: Temperature contrast. Describe: Cool/warm, location, intensity. Connect: How does this subtle awareness change your mental state?',
    steps: [
      { instruction: 'Sit comfortably. Close your eyes. Begin breathing through your nose naturally.', duration: 15 },
      { instruction: 'Focus on the tip of your nose. As you inhale, notice the temperature of the air entering. Is it cool?', duration: 25 },
      { instruction: 'As you exhale, notice the warmth of the air leaving. Feel the contrast - cool in, warm out.', duration: 25 },
      { instruction: 'Now notice where in your nostrils you feel the temperature most clearly. The rim? Deep inside?', duration: 30 },
      { instruction: 'Follow the cool air as it travels deeper. Can you sense it in your sinuses? Your throat?', duration: 30 },
      { instruction: 'On the exhale, trace the warmth from deep in your lungs up through your airways and out your nose.', duration: 30 },
      { instruction: 'This temperature awareness is your interoceptive system working in real-time. Each breath is rich with information.', duration: 25 },
      { instruction: 'Continue for several more breaths. See if you can detect increasingly subtle temperature differences.', duration: 45 },
      { instruction: 'Gently open your eyes. Your sensitivity to internal signals has just increased measurably.', duration: 15 },
    ],
  },
  {
    id: 'progressive-body-scan',
    title: 'Progressive Body Scan',
    subtitle: 'MABT head-to-toe awareness mapping',
    category: 'bodyScanning',
    difficulty: 'beginner',
    durationMinutes: 12,
    benefits: ['Reveals hidden tension patterns', 'Builds comprehensive body literacy', 'Promotes full-body parasympathetic response', 'Foundation of MABT clinical protocol'],
    iconName: 'activity',
    targetConditions: ['anxiety', 'ptsd', 'chronic-pain', 'stress', 'sleep', 'general', 'alexithymia'],
    scienceNote: 'Body scanning is the foundational practice in MABT (Mindful Awareness in Body-oriented Therapy). It systematically activates the insular cortex region by region, building a comprehensive internal body map. MRI studies show increased insular cortex thickness after 8 weeks of daily practice.',
    preparationTips: ['Lie down for best results', 'Cover yourself with a blanket for comfort', 'Dim the lights if possible', 'Allow 15 minutes without interruption'],
    expectedSensations: ['Progressive muscle relaxation wave', 'Discovery of previously unnoticed tension', 'Tingling in extremities', 'Feeling of heaviness (deep relaxation)'],
    contraindications: ['Severe dissociation - use grounding anchors', 'Trauma stored in body - proceed with therapist guidance'],
    researchCitation: 'Price, C. J. & Hooven, C. (2018). Interoceptive awareness skills for emotion regulation: Theory and approach of MABT. Frontiers in Psychology, 9, 798.',
    methodology: 'MABT',
    framework: 'Notice: Sensation in each region. Describe: Quality, intensity, location. Connect: What is each area telling you about your current state?',
    steps: [
      { instruction: 'Lie down comfortably. Close your eyes. Take three deep breaths to settle your nervous system.', duration: 20 },
      { instruction: 'Bring your attention to the top of your head. Notice any sensations: tingling, pressure, warmth, or nothing at all.', duration: 30 },
      { instruction: 'Move awareness to your forehead and temples. Release any tension you find. Imagine it melting away.', duration: 30 },
      { instruction: 'Notice your eyes, cheeks, and jaw. The jaw holds enormous emotional tension. Let it soften and relax.', duration: 30 },
      { instruction: 'Feel your neck and throat. Swallow once and notice the sensation. The throat often holds unexpressed words.', duration: 25 },
      { instruction: 'Scan your shoulders. Are they raised toward your ears? Let them drop. This is where stress accumulates.', duration: 30 },
      { instruction: 'Move down through your upper arms, elbows, forearms, and into your hands. Notice temperature and tingling.', duration: 40 },
      { instruction: 'Feel each finger individually. The fingertips have dense nerve endings. Notice tingling or warmth.', duration: 30 },
      { instruction: 'Bring attention to your chest. Notice the rise and fall of breathing. Any tightness or openness?', duration: 35 },
      { instruction: 'Scan your upper back and mid-back. Notice any tightness or holding. These muscles guard your heart.', duration: 30 },
      { instruction: 'Feel your stomach and lower abdomen. The gut contains 500 million neurons. Notice any butterflies or tightness.', duration: 30 },
      { instruction: 'Move to your lower back and hips. Let them settle into the surface beneath you.', duration: 30 },
      { instruction: 'Scan down through your thighs, knees, and calves. Notice heaviness or lightness.', duration: 30 },
      { instruction: 'Feel your ankles, the soles of your feet, and each toe. Your feet literally ground you.', duration: 30 },
      { instruction: 'Now expand your awareness to your whole body at once. Feel it as one connected, sensing organism.', duration: 45 },
      { instruction: 'Rest in this full-body awareness. You have just activated your entire insular cortex map.', duration: 30 },
      { instruction: 'Gently wiggle your fingers and toes. Open your eyes slowly when you feel ready.', duration: 15 },
    ],
  },
  {
    id: 'focused-body-scan',
    title: 'Focused Area Deep Dive',
    subtitle: 'Precision awareness of one body region',
    category: 'bodyScanning',
    difficulty: 'intermediate',
    durationMinutes: 10,
    benefits: ['Develops microscopic interoceptive precision', 'Identifies subtle signal patterns', 'Releases chronic holding patterns', 'Builds advanced body literacy'],
    iconName: 'activity',
    targetConditions: ['chronic-pain', 'anxiety', 'alexithymia', 'general'],
    scienceNote: 'Focused attention on a single body region creates deeper insular cortex activation than broad scanning. This technique is used in MABT Level 2 for developing discriminative interoceptive awareness.',
    preparationTips: ['Choose an area that calls your attention', 'Areas of mild discomfort often yield the most insight', 'Avoid areas of acute pain for first attempts'],
    expectedSensations: ['Increased sensitivity in chosen area', 'Sensation evolution over time', 'Discovery of sub-sensations within larger sensations', 'Possible emotional release'],
    contraindications: ['Chronic pain areas - start with neutral areas first', 'Trauma-associated body regions - work with therapist'],
    researchCitation: 'Farb et al. (2013). Interoception, contemplative practice, and health. Frontiers in Psychology, 6, 763.',
    methodology: 'MABT',
    framework: 'Notice: What sensation is present? Describe: Shape, edges, quality, intensity. Connect: What information is this sensation carrying?',
    steps: [
      { instruction: 'Sit or lie comfortably. Choose one area of your body that calls your attention right now.', duration: 20 },
      { instruction: 'Take five deep breaths to center yourself and activate your body awareness.', duration: 30 },
      { instruction: 'Bring all your attention to your chosen area. What do you notice first? Name it silently.', duration: 30 },
      { instruction: 'Is there warmth or coolness? Tightness or openness? Tingling or numbness? Layer by layer, investigate.', duration: 40 },
      { instruction: 'Breathe into that area. Imagine your breath flowing directly there, bringing oxygen and awareness.', duration: 40 },
      { instruction: 'Notice the edges of the sensation. Where does it begin and end? Is it well-defined or diffuse?', duration: 40 },
      { instruction: 'Does the sensation have a shape? A color? A texture? These synesthetic impressions reveal deep processing.', duration: 40 },
      { instruction: 'Has the sensation changed since you started paying attention? Observation often transforms what is observed.', duration: 40 },
      { instruction: 'Send a sense of acceptance to this area. Whatever you find is simply information from your body.', duration: 40 },
      { instruction: 'Take three more breaths directed to this area. Thank your body for the information.', duration: 25 },
      { instruction: 'Slowly expand your awareness back to your whole body. Notice the contrast.', duration: 20 },
      { instruction: 'Open your eyes. Reflect on what you discovered. Your precision awareness has deepened.', duration: 15 },
    ],
  },
  {
    id: 'quick-body-check',
    title: 'Quick Body Check',
    subtitle: '2-minute MABT micro-practice',
    category: 'bodyScanning',
    difficulty: 'beginner',
    durationMinutes: 2,
    benefits: ['Perfect for busy schedules', 'Interrupts stress accumulation', 'Prevents tension buildup', 'Maintains daily practice streak easily'],
    iconName: 'activity',
    targetConditions: ['stress', 'general', 'anxiety'],
    scienceNote: 'Even 2-minute body awareness breaks can interrupt the stress-tension feedback loop. Kelly Mahler\'s research shows micro-practices maintain interoceptive gains between longer sessions.',
    preparationTips: ['Can be done seated at desk', 'No special preparation needed', 'Eyes open or closed'],
    expectedSensations: ['Quick tension discovery', 'Breath awareness shift', 'Brief relaxation response'],
    contraindications: ['None - suitable for all'],
    researchCitation: 'Mahler, K. (2017). Interoception: The Eighth Sensory System. AAPC Publishing.',
    methodology: 'mindfulness',
    framework: 'Notice: 3 sensations. Describe: Name each one. Connect: What do they tell you about right now?',
    steps: [
      { instruction: 'Pause whatever you are doing. Take one deep breath. Close your eyes if comfortable.', duration: 10 },
      { instruction: 'Scan quickly: head, shoulders, chest, stomach, hands. Where is tension hiding?', duration: 20 },
      { instruction: 'Name 2-3 sensations silently. Tight jaw. Shallow breath. Warm hands.', duration: 15 },
      { instruction: 'Take two slow breaths, directing each exhale toward the tightest area.', duration: 20 },
      { instruction: 'Release. Open your eyes. You just reset your nervous system in under 2 minutes.', duration: 10 },
    ],
  },
  {
    id: 'tension-release',
    title: 'Progressive Muscle Relaxation',
    subtitle: 'Jacobson\'s evidence-based protocol',
    category: 'tension',
    difficulty: 'beginner',
    durationMinutes: 10,
    benefits: ['Reduces physical stress markers by 44%', 'Teaches the contrast between tension and relaxation', 'Clinically proven for insomnia treatment', 'Activates proprioceptive-interoceptive bridge'],
    iconName: 'zap',
    targetConditions: ['anxiety', 'stress', 'sleep', 'chronic-pain', 'ptsd', 'general'],
    scienceNote: 'Progressive Muscle Relaxation (PMR) was developed by Edmund Jacobson in 1938 and remains one of the most researched relaxation techniques. It works by creating deliberate tension followed by release, teaching the nervous system to recognize and release unconscious holding.',
    preparationTips: ['Wear comfortable clothing', 'Lie down or sit in a supportive chair', 'Set aside 15 minutes without interruption', 'Tense muscles firmly but not painfully'],
    expectedSensations: ['Clear contrast between tension and relaxation', 'Progressive heaviness and warmth', 'Possible muscle twitching (normal)', 'Deep relaxation by final release'],
    contraindications: ['Acute muscle injury - skip that area', 'Severe muscle spasms - use gentler tension', 'High blood pressure - avoid intense tensing'],
    researchCitation: 'Jacobson, E. (1938). Progressive Relaxation. University of Chicago Press. Meta-analysis: Manzoni et al. (2008). Relaxation training for anxiety. Anxiety, Stress & Coping, 21(1), 85-97.',
    methodology: 'somatic',
    framework: 'Notice: Tension vs relaxation contrast. Describe: Location, intensity, quality of release. Connect: Where does your body store stress?',
    steps: [
      { instruction: 'Lie on your back or sit in a supportive chair. Close your eyes. This is Dr. Jacobson\'s proven protocol.', duration: 15 },
      { instruction: 'Clench both fists as tight as you can. Hold the tension. Feel every muscle fiber engaged.', duration: 8 },
      { instruction: 'Release your fists completely. Notice the flood of relaxation. This contrast is the key to PMR.', duration: 15 },
      { instruction: 'Tense your forearms by bending your wrists toward you. Hold firmly.', duration: 8 },
      { instruction: 'Release. Feel the warmth flow into your arms as blood returns.', duration: 15 },
      { instruction: 'Shrug your shoulders up to your ears as high as possible. Hold tight.', duration: 8 },
      { instruction: 'Drop them completely. Feel the weight release. Notice how much tension you were carrying.', duration: 15 },
      { instruction: 'Scrunch your face: squeeze eyes, purse lips, wrinkle nose. Hold everything tight.', duration: 8 },
      { instruction: 'Let your face soften completely. Feel the smoothness and release.', duration: 15 },
      { instruction: 'Press your shoulder blades together behind you. Hold the squeeze.', duration: 8 },
      { instruction: 'Release. Notice the expansion across your back and chest.', duration: 15 },
      { instruction: 'Tighten your abs as if bracing for impact. Engage your core firmly.', duration: 8 },
      { instruction: 'Release. Let your belly be soft and relaxed. No guarding needed.', duration: 15 },
      { instruction: 'Squeeze your glutes and thighs together. Hold the tension.', duration: 8 },
      { instruction: 'Release. Feel heaviness settle into your lower body.', duration: 15 },
      { instruction: 'Point your toes away from you, tensing your calves. Hold.', duration: 8 },
      { instruction: 'Release. Let your feet fall naturally to the sides.', duration: 15 },
      { instruction: 'Now tense your entire body at once. Every muscle. Hold for 5 seconds.', duration: 10 },
      { instruction: 'Release everything simultaneously. Melt into total relaxation. Feel the wave.', duration: 30 },
      { instruction: 'Rest here. Your muscle tension has decreased by an average of 44%. Notice how different your body feels.', duration: 30 },
    ],
  },
  {
    id: 'jaw-neck-release',
    title: 'Jaw & Neck Release',
    subtitle: 'Release your primary stress storage',
    category: 'tension',
    difficulty: 'beginner',
    durationMinutes: 6,
    benefits: ['Relieves tension headaches at source', 'Reduces unconscious jaw clenching (bruxism)', 'Eases neck stiffness from stress posture', 'Releases emotional holding in throat area'],
    iconName: 'zap',
    targetConditions: ['stress', 'anxiety', 'chronic-pain', 'general'],
    scienceNote: 'The jaw and neck contain some of the highest densities of proprioceptive receptors in the body. Tension here directly impacts the trigeminal and vagus nerves, creating a feedback loop with emotional stress.',
    preparationTips: ['Sit upright for best neck mobility', 'Move slowly - never force range of motion', 'Massage is more effective after warming up'],
    expectedSensations: ['Clicking or popping in jaw joint (normal)', 'Stretch along neck muscles', 'Relief spreading to temples and scalp', 'Possible yawning (parasympathetic activation)'],
    contraindications: ['TMJ disorder - gentler movements only', 'Cervical spine injury - avoid head rolls'],
    researchCitation: 'Slade et al. (2016). Facial pain, TMD, and oral parafunction. Journal of Dental Research, 95(10), 1084-1092.',
    methodology: 'somatic',
    framework: 'Notice: Where is tension hiding? Describe: Quality and location. Connect: What stress is being held here?',
    steps: [
      { instruction: 'Sit upright. Notice where your tongue rests in your mouth right now. Tension often starts here.', duration: 15 },
      { instruction: 'Let your jaw hang slightly open. Feel the space between your upper and lower teeth. This is the resting position.', duration: 15 },
      { instruction: 'Slowly move your jaw side to side. Notice any clicking, tightness, or asymmetry.', duration: 20 },
      { instruction: 'Open your mouth wide, then close slowly. Repeat three times. Notice the range of motion.', duration: 20 },
      { instruction: 'Place your fingertips on your jaw joints (in front of your ears). Massage in small circles. Release the masseter muscle.', duration: 25 },
      { instruction: 'Drop your chin to your chest. Feel the stretch along the back of your neck and into your upper back.', duration: 20 },
      { instruction: 'Slowly roll your head to the right. Pause where you feel tension. Breathe into that spot.', duration: 20 },
      { instruction: 'Roll your head back to center, then to the left. Breathe into tight areas.', duration: 20 },
      { instruction: 'Return to center. Shrug shoulders up, hold 5 seconds, then drop them.', duration: 15 },
      { instruction: 'Repeat the shrug two more times. Lift higher each time, then release more completely.', duration: 30 },
      { instruction: 'Sit still. Notice how your jaw and neck feel now compared to when you started. Name the difference.', duration: 20 },
    ],
  },
  {
    id: 'micro-tension-detection',
    title: 'Micro-Tension Detection',
    subtitle: 'Find invisible stress patterns',
    category: 'tension',
    difficulty: 'advanced',
    durationMinutes: 8,
    benefits: ['Reveals unconscious holding patterns', 'Prevents chronic tension buildup', 'Develops expert-level body literacy', 'Maps personal stress signature'],
    iconName: 'zap',
    targetConditions: ['chronic-pain', 'anxiety', 'stress', 'alexithymia'],
    scienceNote: 'Micro-tensions are below-conscious-threshold muscle activations that accumulate throughout the day. Training awareness of these subtle signals is Level 3 MABT practice - distinguishing between signal layers.',
    preparationTips: ['Best practiced in a very quiet environment', 'After initial relaxation', 'Requires focused, patient attention'],
    expectedSensations: ['Discovery of previously unknown tension spots', 'Tiny muscle twitches as awareness arrives', 'Release of subtle holding', 'Surprise at hidden tension patterns'],
    contraindications: ['Perfectionism about relaxation can increase tension - stay curious, not forceful'],
    researchCitation: 'Mehling et al. (2012). The Multidimensional Assessment of Interoceptive Awareness (MAIA). PLoS ONE, 7(11).',
    methodology: 'MABT',
    framework: 'Notice: Sub-threshold tension. Describe: Micro-location, micro-intensity. Connect: What habitual stress pattern creates this holding?',
    steps: [
      { instruction: 'Lie down. Spend 2 minutes doing a full body relaxation. Let everything go as much as possible.', duration: 30 },
      { instruction: 'Now bring microscopic attention to your face. Is there the slightest furrowing of your brow?', duration: 30 },
      { instruction: 'Check the tiny muscles around your eyes. Are they truly relaxed or slightly squinting?', duration: 25 },
      { instruction: 'Your tongue - is it pressed against the roof of your mouth? This is one of the most common micro-tensions.', duration: 25 },
      { instruction: 'Scan the muscles at the base of your skull. Even a millimeter of tension here can cause headaches.', duration: 30 },
      { instruction: 'Check the muscles between your shoulder blades. They often guard the heart unconsciously.', duration: 30 },
      { instruction: 'Your hands - are your fingers truly loose, or slightly curled? Uncurl them completely.', duration: 25 },
      { instruction: 'Your toes - are they gripping? Even slightly? Release them fully into the surface.', duration: 25 },
      { instruction: 'Your pelvic floor and deep abdominal muscles - are they bracing? Let your entire core soften.', duration: 30 },
      { instruction: 'Now scan everywhere simultaneously. You have likely found 3-5 micro-tensions you didn\'t know existed.', duration: 30 },
      { instruction: 'These subtle holding patterns are your body\'s stress signature. Now that you know them, you can release them throughout your day.', duration: 30 },
    ],
  },
  {
    id: 'temperature-awareness',
    title: 'Temperature Awareness',
    subtitle: 'Map your body\'s thermal landscape',
    category: 'temperature',
    difficulty: 'beginner',
    durationMinutes: 7,
    benefits: ['Develops thermal interoceptive channel', 'Enhances precision body awareness', 'Reveals autonomic nervous system patterns', 'Blood flow awareness indicates stress level'],
    iconName: 'thermometer',
    targetConditions: ['general', 'alexithymia', 'anxiety'],
    scienceNote: 'Temperature perception is mediated by thermoreceptors throughout the body. Peripheral temperature decreases with sympathetic (stress) activation and increases with parasympathetic (relaxation) activation. Warm hands = calm nervous system.',
    preparationTips: ['Room temperature environment is ideal', 'Remove gloves or thick socks for better detection', 'Hands and feet show the most temperature variation'],
    expectedSensations: ['Temperature gradients across body', 'Cool extremities (normal stress response)', 'Warm core relative to limbs', 'Temperature shifts with breathing'],
    contraindications: ['Raynaud\'s syndrome - avoid cold focus areas'],
    researchCitation: 'Critchley & Harrison (2013). Visceral influences on brain and behavior. Neuron, 77(4), 624-638.',
    methodology: 'MABT',
    framework: 'Notice: Temperature in each region. Describe: Warm/cool/hot/cold, gradient direction. Connect: What does your thermal map say about your stress level?',
    steps: [
      { instruction: 'Sit comfortably with your hands resting on your thighs. Close your eyes.', duration: 15 },
      { instruction: 'Focus on your hands. Notice their temperature. Are they warm or cool? This reflects your autonomic state.', duration: 25 },
      { instruction: 'Compare your left hand to your right. Is one warmer? Asymmetry is common and informative.', duration: 25 },
      { instruction: 'Now notice your face. Is your forehead warm or cool? What about your cheeks?', duration: 25 },
      { instruction: 'Focus on the tip of your nose. It is often one of the coolest parts of the body - far from your core.', duration: 25 },
      { instruction: 'Notice the temperature of the air as you inhale. Cool air entering your nostrils via thermoreceptors.', duration: 25 },
      { instruction: 'As you exhale, notice the warmer air leaving. Your body has heated it. Feel the contrast.', duration: 25 },
      { instruction: 'Bring attention to your feet. Are they warm or cold? Your autonomic system controls peripheral blood flow.', duration: 25 },
      { instruction: 'Now scan from head to toe. Create a complete temperature map of your body. Cool areas, warm areas.', duration: 40 },
      { instruction: 'The warmest areas typically have the most blood flow. Cool extremities indicate sympathetic activation (stress).', duration: 30 },
      { instruction: 'As you relax, you may notice your hands and feet warming. This is your parasympathetic system activating.', duration: 25 },
      { instruction: 'Take a deep breath. Open your eyes. You now have a thermal snapshot of your autonomic state.', duration: 15 },
    ],
  },
  {
    id: 'warm-hands',
    title: 'Warm Hands Biofeedback',
    subtitle: 'Direct blood flow with intention',
    category: 'temperature',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Demonstrates voluntary autonomic control', 'Reduces stress response measurably', 'Used in clinical biofeedback for migraine treatment', 'Builds confidence in mind-body connection'],
    iconName: 'thermometer',
    targetConditions: ['stress', 'anxiety', 'chronic-pain', 'general'],
    scienceNote: 'Hand-warming biofeedback is one of the oldest biofeedback techniques, clinically proven for migraine prevention. It works by reducing sympathetic vasoconstriction, allowing blood to flow to the periphery. Success rate: 40-60% migraine reduction.',
    preparationTips: ['Start with cool hands for measurable change', 'A thermometer can provide objective feedback', 'Avoid trying too hard - gentle intention works best'],
    expectedSensations: ['Tingling as blood flow increases', 'Gradual warmth spreading through hands', 'Possible color change in palms (pinkish)', 'Deep sense of relaxation'],
    contraindications: ['None - safe for all populations'],
    researchCitation: 'Nestoriuc et al. (2008). Biofeedback treatment for headache disorders. Applied Psychophysiology and Biofeedback, 33(3), 125-140.',
    methodology: 'somatic',
    framework: 'Notice: Hand temperature baseline. Describe: Changes during practice. Connect: What does voluntary temperature control teach you about mind-body influence?',
    steps: [
      { instruction: 'Sit with your hands resting palms-up on your thighs. Close your eyes.', duration: 15 },
      { instruction: 'Notice the current temperature of your hands. Rate it: cold, cool, neutral, warm, or hot.', duration: 20 },
      { instruction: 'Take five slow breaths to relax your body. With each exhale, let go of tension.', duration: 30 },
      { instruction: 'Imagine warm sunlight shining directly onto your palms. Feel the gentle heat.', duration: 30 },
      { instruction: 'Visualize the warmth spreading from your palms through each finger, one by one.', duration: 40 },
      { instruction: 'With each exhale, imagine breathing warmth down your arms and into your hands.', duration: 40 },
      { instruction: 'Feel the blood flowing down your arms and pooling warmly in your hands. Your arterioles are dilating.', duration: 40 },
      { instruction: 'Your hands are growing warmer. Feel the tingling of increased blood flow. This is real - you are changing your physiology.', duration: 40 },
      { instruction: 'Continue breathing warmth into your hands. No effort, just gentle intention. Your autonomic system is responding.', duration: 60 },
      { instruction: 'Notice how your hands feel now compared to when you started. Most people experience 2-4 degree warming.', duration: 20 },
      { instruction: 'This ability to direct blood flow demonstrates that your mind can influence your autonomic nervous system. That is powerful.', duration: 15 },
      { instruction: 'Open your eyes. Carry this awareness with you. You have more control over your body than you may have believed.', duration: 15 },
    ],
  },
  {
    id: 'gut-feeling-scan',
    title: 'Gut Feeling Awareness',
    subtitle: 'Listen to your enteric nervous system',
    category: 'gut',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Strengthens gut-brain axis communication', 'Enhances intuitive decision-making', 'Reduces stress-related digestive issues', 'Activates 500 million enteric neurons'],
    iconName: 'circle',
    targetConditions: ['eating-disorders', 'anxiety', 'stress', 'alexithymia', 'general'],
    scienceNote: 'The enteric nervous system contains 500 million neurons and produces 95% of the body\'s serotonin. The vagus nerve sends 80% of signals from gut to brain. "Gut feelings" are real interoceptive signals that influence decision-making and emotional processing.',
    preparationTips: ['Practice 1-2 hours after a light meal for best gut signals', 'Place a hand on your lower abdomen for tactile feedback', 'A quiet environment helps detect subtle signals'],
    expectedSensations: ['Gurgling or movement sensations', 'Warmth in abdominal area', 'Emotional responses to gut awareness', 'Sense of gut "knowing" or intuition'],
    contraindications: ['Active eating disorder - work with therapist', 'IBS flare-up - may increase awareness of discomfort'],
    researchCitation: 'Mayer, E. A. (2011). Gut feelings: the emerging biology of gut-brain communication. Nature Reviews Neuroscience, 12(8), 453-466.',
    methodology: 'MABT',
    framework: 'Notice: Gut signals. Describe: Gurgling, tension, warmth, butterflies. Connect: What emotional information is your gut carrying?',
    steps: [
      { instruction: 'Sit or lie comfortably. Place one hand lightly on your lower abdomen, below your navel.', duration: 15 },
      { instruction: 'Close your eyes. Take five slow breaths, letting your belly expand with each inhale. Feel your hand rise and fall.', duration: 30 },
      { instruction: 'Focus all attention on the area beneath your hand. This region houses your "second brain." What do you notice?', duration: 30 },
      { instruction: 'Notice any gurgling, movement, or warmth. Your gut is always active - 500 million neurons working constantly.', duration: 40 },
      { instruction: 'Is there any tightness or knotting? Gut tension often signals emotional holding - anxiety, worry, or unprocessed feelings.', duration: 30 },
      { instruction: 'Breathe softly into your belly. Imagine the breath soothing this area. Your vagus nerve is the bridge.', duration: 40 },
      { instruction: 'Think of something that makes you slightly nervous. Notice your gut response instantly. This is real-time interoception.', duration: 30 },
      { instruction: 'Now think of something comforting and safe. How does your gut respond differently? Notice the contrast.', duration: 30 },
      { instruction: 'Return to neutral awareness. Simply observe without judgment. Your gut is always communicating.', duration: 40 },
      { instruction: 'Your gut produces 95% of your body\'s serotonin. Listening to it is literally tuning into your happiness chemistry.', duration: 20 },
      { instruction: 'Remove your hand. Maintain the internal awareness. Open your eyes. Trust what your gut tells you.', duration: 15 },
    ],
  },
  {
    id: 'hunger-fullness-check',
    title: 'Hunger & Fullness Awareness',
    subtitle: 'Distinguish physical from emotional hunger',
    category: 'gut',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Develops hunger-satiety interoception', 'Reduces emotional eating patterns', 'Supports eating disorder recovery', 'Improves natural portion control'],
    iconName: 'circle',
    targetConditions: ['eating-disorders', 'general', 'alexithymia'],
    scienceNote: 'People with eating disorders show impaired hunger-fullness interoception. Training this channel helps restore natural hunger/satiety signals that have been overridden by emotional eating, restriction, or cognitive rules about food.',
    preparationTips: ['Practice at various times - before meals, during meals, between meals', 'Be honest about what you feel, not what you think you should feel', 'No judgment about hunger or fullness level'],
    expectedSensations: ['Stomach emptiness or fullness', 'Salivation changes', 'Energy level shifts', 'Emotional urges vs physical signals'],
    contraindications: ['Active restrictive eating disorder - practice with therapist guidance only', 'Binge eating disorder - use with professional support'],
    researchCitation: 'Merwin et al. (2010). Interoceptive awareness in eating disorders. Eating Behaviors, 11(1), 1-5.',
    methodology: 'mindfulness',
    framework: 'Notice: Physical hunger signals. Describe: Location, intensity 1-10, quality. Connect: Is this body hunger or emotional hunger?',
    steps: [
      { instruction: 'Pause and bring attention to your stomach area. Rate your hunger on a 1-10 scale. 1 = painfully empty. 10 = painfully full.', duration: 20 },
      { instruction: 'Where exactly do you feel hunger or fullness? Stomach? Throat? Mouth? Whole body?', duration: 20 },
      { instruction: 'Physical hunger builds gradually and responds to any food. Emotional hunger is sudden and craves specifics. Which is this?', duration: 25 },
      { instruction: 'Notice your energy level. True hunger often comes with low energy, difficulty concentrating, or mild irritability.', duration: 20 },
      { instruction: 'Check your mouth. Is there salivation? Dryness? These are interoceptive signals about your body\'s food needs.', duration: 20 },
      { instruction: 'If you are eating, pause after several bites. Has the hunger number changed? Where are you on the 1-10 scale now?', duration: 25 },
      { instruction: 'The goal is comfortable fullness at 6-7, not stuffed at 9-10. Your body signals the right amount if you listen.', duration: 20 },
      { instruction: 'Practice this check 3 times daily - before, during, and after meals. Your hunger-fullness awareness will sharpen rapidly.', duration: 15 },
    ],
  },
  {
    id: 'shoulder-check',
    title: 'Shoulder Stress Release',
    subtitle: 'Release your body\'s stress barometer',
    category: 'tension',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Relieves chronic shoulder elevation', 'Reduces upper back pain', 'Improves breathing depth by 15%', 'Interrupts stress posture pattern'],
    iconName: 'zap',
    targetConditions: ['stress', 'anxiety', 'chronic-pain', 'general'],
    scienceNote: 'The upper trapezius is the most common site of stress-related muscle tension. Chronic elevation reduces breathing capacity and creates a sympathetic nervous system feedback loop that perpetuates anxiety.',
    preparationTips: ['Stand or sit tall', 'Can be done at your desk', 'Practice every 1-2 hours for best results'],
    expectedSensations: ['Immediate relief with each shrug-release', 'Shoulders dropping significantly from starting position', 'Improved breathing depth', 'Warmth in released muscles'],
    contraindications: ['Shoulder injury - move within pain-free range'],
    researchCitation: 'Lundberg et al. (2002). Trapezius muscle activity and muscular complaints in psychosocial stress. Psychoneuroendocrinology, 27(5), 595-607.',
    methodology: 'somatic',
    framework: 'Notice: Shoulder position. Describe: Height, tension level. Connect: What stress is your body holding in your shoulders right now?',
    steps: [
      { instruction: 'Stand or sit tall. Notice where your shoulders are right now without changing them.', duration: 10 },
      { instruction: 'Are they crept up toward your ears? Most people carry chronic tension here without realizing it.', duration: 15 },
      { instruction: 'Inhale and deliberately raise your shoulders as high as possible toward your ears.', duration: 8 },
      { instruction: 'Hold them there. Feel the tension. This exaggerated position mirrors chronic stress posture.', duration: 8 },
      { instruction: 'Exhale and let them drop completely. Feel the contrast. This is what relaxed shoulders feel like.', duration: 10 },
      { instruction: 'Again: inhale, shoulders up. Feel the effort and holding.', duration: 8 },
      { instruction: 'Exhale, let them fall. Notice the relief flooding the muscles.', duration: 10 },
      { instruction: 'One more time: inhale, lift high. Hold the tension.', duration: 8 },
      { instruction: 'Exhale and release completely. Let gravity do the work. Your trapezius is releasing.', duration: 10 },
      { instruction: 'Roll your shoulders backward three times slowly. Feel each muscle engaging and releasing.', duration: 20 },
      { instruction: 'Now forward three times. Notice the different muscles involved.', duration: 20 },
      { instruction: 'Sit still. Notice how much lower your shoulders sit now. Set an intention to check them every hour today.', duration: 20 },
    ],
  },
  {
    id: 'cold-exposure-intro',
    title: 'Cold Sensation Introduction',
    subtitle: 'Vagal nerve activation through cold',
    category: 'exposure',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Activates the dive reflex (instant calm)', 'Builds distress tolerance', 'Stimulates vagus nerve strongly', 'Increases resilience to uncomfortable sensations'],
    iconName: 'shield',
    targetConditions: ['panic', 'anxiety', 'stress', 'general'],
    scienceNote: 'Cold exposure activates the mammalian dive reflex through the trigeminal nerve, causing rapid parasympathetic activation. Heart rate drops, blood pressure normalizes, and anxiety decreases within 30 seconds. This is a key DBT distress tolerance skill.',
    preparationTips: ['Have a glass of cold water or ice pack ready', 'Start with hands before face for gentler introduction', 'Have a towel nearby'],
    expectedSensations: ['Initial shock sensation', 'Rapid heart rate change', 'Increased alertness followed by calm', 'Tingling as blood flow adjusts'],
    contraindications: ['Raynaud\'s syndrome', 'Severe cardiac conditions', 'Cold urticaria (cold allergy)'],
    researchCitation: 'Kox et al. (2014). Voluntary activation of the sympathetic nervous system and attenuation of the innate immune response. PNAS, 111(20), 7379-7384.',
    methodology: 'exposure',
    framework: 'Notice: Cold sensation + body response. Describe: Temperature, heart rate change, breathing shift. Connect: How quickly does your nervous system adapt?',
    steps: [
      { instruction: 'You will need a cup of cold water or ice pack. Hold it in both hands.', duration: 15 },
      { instruction: 'Notice the temperature against your palms. Rate the coldness 1-10. What does your body do in response?', duration: 15 },
      { instruction: 'Take a deep breath and hold the cold object firmly. Notice the initial discomfort.', duration: 20 },
      { instruction: 'Keep holding. Your body is adapting. Notice: has the discomfort changed in quality or intensity?', duration: 25 },
      { instruction: 'Check your heart rate. Cold exposure typically triggers a brief increase, then a pronounced decrease. Can you feel it?', duration: 20 },
      { instruction: 'This is the dive reflex - your body\'s ancient survival mechanism. It creates instant parasympathetic activation.', duration: 20 },
      { instruction: 'Set the cold object down. Notice the warmth flooding back into your hands.', duration: 15 },
      { instruction: 'The contrast between cold and warm is powerful interoceptive information. Your nervous system just recalibrated.', duration: 15 },
      { instruction: 'Optional next step: splash cold water on your face to activate the trigeminal nerve directly. This is even more powerful for anxiety.', duration: 20 },
      { instruction: 'Rest and observe. Notice how calm you feel. Cold exposure is one of the fastest-acting anxiety interventions available.', duration: 20 },
    ],
  },
  {
    id: 'breath-counting',
    title: 'Mindful Breath Counting',
    subtitle: 'Ancient attention anchor technique',
    category: 'breathing',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Improves sustained attention', 'Interrupts rumination loops', 'Builds foundational breath awareness', 'Reduces mind-wandering by 30%'],
    iconName: 'wind',
    targetConditions: ['anxiety', 'stress', 'depression', 'general'],
    scienceNote: 'Breath counting activates the anterior cingulate cortex, the brain\'s conflict monitor, which strengthens executive attention. Research shows it reduces mind-wandering and improves emotional regulation within days of practice.',
    preparationTips: ['Sit comfortably with eyes closed or softly focused', 'No need to control breath rhythm', 'When you lose count, simply restart - this IS the practice'],
    expectedSensations: ['Gradually slowing breath', 'Increased mental clarity', 'Moments of losing count (normal)', 'Deepening calm with each round'],
    contraindications: ['None - suitable for complete beginners'],
    researchCitation: 'Levinson et al. (2014). A mind you can count on: validating breath counting as a behavioral measure of mindfulness. Frontiers in Psychology, 5, 1202.',
    methodology: 'mindfulness',
    framework: 'Notice: Each breath. Describe: Quality of attention, ease of counting. Connect: What happens to your mental state as breath slows?',
    steps: [
      { instruction: 'Sit comfortably. Let your breath flow naturally without controlling it. Close your eyes.', duration: 15 },
      { instruction: 'On your next exhale, silently count "one." Just the exhale, not the inhale.', duration: 10 },
      { instruction: 'Inhale naturally. On the next exhale, count "two."', duration: 10 },
      { instruction: 'Continue counting each exhale up to ten. If you lose count, simply start again at one.', duration: 80 },
      { instruction: 'When you reach ten, start back at one. The restart is not failure - it is awareness.', duration: 10 },
      { instruction: 'If you lose count, notice it without judgment. Restart at one. This moment of noticing IS mindfulness.', duration: 15 },
      { instruction: 'Continue this practice. Count exhales from one to ten, cycling back to one.', duration: 90 },
      { instruction: 'Notice how your breathing may naturally slow and deepen. Your nervous system is responding to the attention.', duration: 20 },
      { instruction: 'Let go of the counting. Simply observe your breath for a moment. Notice the quality of attention.', duration: 20 },
      { instruction: 'Open your eyes when you feel ready. Your anterior cingulate cortex just got a workout.', duration: 10 },
    ],
  },
  {
    id: 'straw-breathing',
    title: 'Straw Breathing',
    subtitle: 'Controlled respiratory resistance',
    category: 'breathing',
    difficulty: 'intermediate',
    durationMinutes: 5,
    benefits: ['Extends exhale naturally for vagal activation', 'Builds respiratory interoceptive awareness', 'Used in interoceptive exposure for breathlessness tolerance', 'Strengthens diaphragm'],
    iconName: 'wind',
    targetConditions: ['panic', 'anxiety', 'stress'],
    scienceNote: 'Breathing through a straw creates controlled resistance that naturally extends the exhale phase. In interoceptive exposure therapy, it safely induces mild breathlessness to reduce panic sensitivity to respiratory sensations.',
    preparationTips: ['Use a regular drinking straw', 'Start with exhale only through straw, inhale through nose', 'Stop if lightheaded'],
    expectedSensations: ['Mild breathlessness (intended and safe)', 'Increased breathing awareness', 'Diaphragm engagement', 'Gradual calming despite initial discomfort'],
    contraindications: ['Severe asthma - consult physician', 'Active panic attack - use box breathing instead', 'COPD - modify or avoid'],
    researchCitation: 'Craske et al. (2008). Interoceptive exposure versus breathing retraining within cognitive-behavioural therapy for panic disorder. British Journal of Clinical Psychology, 47(1), 1-14.',
    methodology: 'exposure',
    framework: 'Notice: Breath restriction sensation. Describe: Tightness, effort, air hunger. Connect: Can you stay calm despite respiratory discomfort?',
    steps: [
      { instruction: 'You will need a drinking straw. Hold it ready. Take a few normal breaths to establish baseline.', duration: 15 },
      { instruction: 'Inhale normally through your nose. Then exhale slowly through the straw. Notice the resistance.', duration: 15 },
      { instruction: 'Inhale through your nose again. Exhale through the straw. The restricted airflow extends your exhale naturally.', duration: 15 },
      { instruction: 'Notice the sensations: air moving through the narrow opening, pressure in your cheeks, controlled release.', duration: 20 },
      { instruction: 'Continue the pattern. Nose inhale, straw exhale. Your vagus nerve is being activated by the extended exhale.', duration: 30 },
      { instruction: 'You may notice mild breathlessness. This is intentional and safe. Stay with the sensation - it teaches your brain that it is not dangerous.', duration: 30 },
      { instruction: 'Continue for several more breaths. Your body is learning that respiratory discomfort is manageable.', duration: 40 },
      { instruction: 'Set the straw down. Breathe normally. Notice the contrast - how open and easy normal breathing feels.', duration: 20 },
      { instruction: 'This exercise builds tolerance for breathlessness, which is one of the most common panic triggers. You are training your brain.', duration: 15 },
    ],
  },
  {
    id: 'slow-walking',
    title: 'Slow Walking Awareness',
    subtitle: 'Proprioceptive-interoceptive fusion',
    category: 'movement',
    difficulty: 'beginner',
    durationMinutes: 8,
    benefits: ['Combines movement with body awareness', 'Accessible for those who find stillness difficult', 'Develops proprioceptive-interoceptive integration', 'Grounds attention in the body through motion'],
    iconName: 'move',
    targetConditions: ['ptsd', 'anxiety', 'depression', 'general'],
    scienceNote: 'Walking meditation activates both proprioceptive (body position) and interoceptive (internal sensation) processing simultaneously. For PTSD survivors, gentle movement is often more accessible than seated meditation, which can trigger freeze responses.',
    preparationTips: ['Find a straight path of 10-20 feet', 'Remove shoes if comfortable for better ground feedback', 'Walk at quarter speed of normal pace'],
    expectedSensations: ['Detailed awareness of foot-ground contact', 'Balance micro-adjustments', 'Muscle engagement patterns in legs', 'Breath syncing with steps'],
    contraindications: ['Significant balance issues - stay near a wall', 'Foot pain - wear comfortable shoes'],
    researchCitation: 'Paulus et al. (2012). Subjecting elite athletes to inspiratory breathing load reveals behavioral and neural signatures of optimal performers. PLoS ONE, 7(1).',
    methodology: 'mindfulness',
    framework: 'Notice: Each phase of stepping. Describe: Pressure, temperature, balance, muscle engagement. Connect: How does mindful movement change your relationship with your body?',
    steps: [
      { instruction: 'Stand at one end of your walking path. Feel your feet fully on the ground. Notice the pressure points.', duration: 15 },
      { instruction: 'Take three deep breaths. Feel your body\'s weight distributed through your legs and into the earth.', duration: 20 },
      { instruction: 'Begin to shift your weight to one foot. Feel the other foot lighten. Notice the subtle balance adjustments.', duration: 20 },
      { instruction: 'Lift the light foot slowly. Feel the muscles in your calf and thigh working. Move at quarter speed.', duration: 20 },
      { instruction: 'Place the foot down: heel, then ball, then toes. Feel each phase of contact with the ground.', duration: 20 },
      { instruction: 'Shift your weight to this foot. The other foot lightens. Begin to lift it. Notice everything.', duration: 20 },
      { instruction: 'Continue walking at this very slow pace. Heel, ball, toes. Lift, move, place. Each step is rich with sensation.', duration: 60 },
      { instruction: 'Notice your breath syncing with your steps. Your body naturally coordinates movement and breathing.', duration: 30 },
      { instruction: 'Feel the temperature of the ground. The pressure of your weight. The air moving around your body as you move through it.', duration: 30 },
      { instruction: 'Continue walking. If your mind wanders, gently return attention to the foot that is currently in contact with the ground.', duration: 60 },
      { instruction: 'Gradually slow to a stop. Stand still. Feel the difference between stillness and motion in your body.', duration: 20 },
      { instruction: 'Take a deep breath. You have just practiced proprioceptive-interoceptive integration - awareness of your body in motion.', duration: 15 },
    ],
  },
  {
    id: 'emotion-body-mapping',
    title: 'Emotion Body Mapping',
    subtitle: 'Map where emotions live in your body',
    category: 'bodyScanning',
    difficulty: 'intermediate',
    durationMinutes: 10,
    benefits: ['Builds emotional granularity through body signals', 'Creates personal emotion-body dictionary', 'Reduces alexithymia (emotional blindness)', 'Supports Kelly Mahler\'s Notice-Describe-Connect framework'],
    iconName: 'activity',
    targetConditions: ['alexithymia', 'depression', 'eating-disorders', 'anxiety', 'general'],
    scienceNote: 'Finnish researchers (Nummenmaa et al., 2014) mapped emotion-body associations across cultures, finding universal patterns: anger activates the upper body and hands, sadness deactivates limbs, anxiety activates the chest, happiness activates the whole body.',
    preparationTips: ['Have your body map feature ready for marking afterwards', 'Think of recent emotional experiences', 'No right or wrong answers - your body map is unique'],
    expectedSensations: ['Different body regions activating with different emotions', 'Surprise at where emotions "live"', 'Possible emotional responses during practice', 'Deeper connection between feelings and body'],
    contraindications: ['Severe dissociation - use grounding techniques between emotions', 'Active trauma - work with therapist'],
    researchCitation: 'Nummenmaa et al. (2014). Bodily maps of emotions. PNAS, 111(2), 646-651.',
    methodology: 'MABT',
    framework: 'Notice: Body activation with each emotion. Describe: Location, quality, intensity. Connect: How does knowing your body\'s emotional map help you?',
    steps: [
      { instruction: 'Sit comfortably. Close your eyes. Take three deep breaths to arrive in your body fully.', duration: 20 },
      { instruction: 'We will explore 5 emotions. For each, gently recall the feeling and notice where your body responds.', duration: 15 },
      { instruction: 'First: Joy. Recall a moment of genuine happiness. Where do you feel it? Chest? Face? Whole body? Name the sensations.', duration: 40 },
      { instruction: 'Clear with three breaths. Return to neutral.', duration: 15 },
      { instruction: 'Second: Anxiety. Recall a mildly anxious moment. Where does anxiety live in your body? Chest? Stomach? Throat? What quality?', duration: 40 },
      { instruction: 'Clear with three breaths. You are safe. Return to neutral.', duration: 15 },
      { instruction: 'Third: Sadness. A gentle sadness, not overwhelming. Where is it? Chest? Eyes? A heaviness? A hollowness?', duration: 40 },
      { instruction: 'Clear with three breaths. Let it pass.', duration: 15 },
      { instruction: 'Fourth: Anger. Recall mild frustration. Where does your body activate? Jaw? Hands? Chest? What temperature?', duration: 40 },
      { instruction: 'Clear with three breaths. Release the tension.', duration: 15 },
      { instruction: 'Fifth: Calm. Recall deep peace. Where is calm located? How does it feel? What is its temperature and quality?', duration: 40 },
      { instruction: 'You now have a personal emotion-body map. Each emotion has a unique physical signature. This is your early warning system.', duration: 25 },
      { instruction: 'Open your eyes. Consider marking these patterns in the body map feature to track over time.', duration: 15 },
    ],
  },
  {
    id: 'digestive-awareness',
    title: 'Digestive System Awareness',
    subtitle: 'Full enteric nervous system scan',
    category: 'gut',
    difficulty: 'intermediate',
    durationMinutes: 7,
    benefits: ['Maps the entire digestive interoceptive channel', 'Improves gut-brain communication', 'Supports IBS symptom awareness', 'Develops visceral sensitivity'],
    iconName: 'circle',
    targetConditions: ['eating-disorders', 'stress', 'general', 'alexithymia'],
    scienceNote: 'The digestive system is the largest interoceptive organ system. Gastric interoception is less well-researched than cardiac interoception but equally important for emotional processing and eating behavior.',
    preparationTips: ['Best practiced 1-2 hours after eating', 'Lying down allows better gut signal detection', 'Loose clothing around the waist'],
    expectedSensations: ['Digestive movement and gurgling', 'Temperature differences along digestive tract', 'Pressure sensations', 'Emotional associations with different regions'],
    contraindications: ['Active GI distress - wait for symptom resolution', 'Eating disorder - practice with clinical support'],
    researchCitation: 'Herbert et al. (2012). Interoception across modalities: On the relationship between cardiac awareness and the sensitivity for gastric functions. PLoS ONE, 7(5).',
    methodology: 'MABT',
    framework: 'Notice: Digestive activity. Describe: Location, movement, sound, feeling. Connect: What is your digestive system telling you about your state?',
    steps: [
      { instruction: 'Lie on your back comfortably. Place one hand on your upper stomach, one on your lower abdomen.', duration: 15 },
      { instruction: 'Close your eyes. Take five breaths into your belly, feeling both hands rise and fall.', duration: 25 },
      { instruction: 'Focus on the area behind your upper stomach. This is where your esophagus meets your stomach. Any sensation?', duration: 30 },
      { instruction: 'Move attention to the center of your stomach area. Notice any fullness, emptiness, gurgling, or warmth.', duration: 35 },
      { instruction: 'Shift attention lower to the area around and below your navel. The small intestine processes most nutrients here.', duration: 35 },
      { instruction: 'Notice any movement or peristalsis. Your gut muscles contract rhythmically even at rest.', duration: 30 },
      { instruction: 'Move to your lower left abdomen. The large intestine curves here. Any pressure or sensation?', duration: 25 },
      { instruction: 'Now take a broad view - sense your entire digestive system as one living, working organ system.', duration: 35 },
      { instruction: 'Your enteric nervous system is always active, always communicating with your brain. You are learning to listen.', duration: 20 },
      { instruction: 'Open your eyes. You have just tuned into a system containing 500 million neurons. That awareness matters.', duration: 15 },
    ],
  },
  {
    id: 'warmth-coolness-scan',
    title: 'Warmth & Coolness Scan',
    subtitle: 'Full-body thermal mapping',
    category: 'temperature',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Comprehensive thermal interoceptive training', 'Reveals autonomic nervous system balance', 'Develops discriminative awareness between body regions', 'Detects inflammation and stress patterns'],
    iconName: 'thermometer',
    targetConditions: ['chronic-pain', 'general', 'alexithymia', 'stress'],
    scienceNote: 'Thermal interoception is mediated by TRPV (warmth) and TRPM (cold) receptor channels. Temperature asymmetries can indicate stress patterns, inflammation, or autonomic imbalance. Thermal scanning trains the insular cortex to process these signals consciously.',
    preparationTips: ['Moderate room temperature', 'Minimal clothing for better detection', 'Lying down for full body access'],
    expectedSensations: ['Temperature gradients head to toe', 'Core warmth vs peripheral coolness', 'Unexpected warm or cool spots', 'Changes as you attend to each area'],
    contraindications: ['None - safe for all populations'],
    researchCitation: 'Craig, A. D. (2002). How do you feel? Interoception: the sense of the physiological condition of the body. Nature Reviews Neuroscience, 3(8), 655-666.',
    methodology: 'MABT',
    framework: 'Notice: Temperature in each zone. Describe: Degree (cold/cool/neutral/warm/hot), distribution. Connect: What does your thermal map reveal about your stress level?',
    steps: [
      { instruction: 'Lie comfortably. Close your eyes. We will create a complete thermal map of your body.', duration: 15 },
      { instruction: 'Start at your scalp. Notice its temperature. The head is one of the warmest regions due to brain metabolism.', duration: 25 },
      { instruction: 'Move to your face: forehead, cheeks, nose. The nose tip is typically the coolest facial area.', duration: 25 },
      { instruction: 'Feel your neck and throat. Notice the warmth from major blood vessels (carotid arteries) passing through.', duration: 25 },
      { instruction: 'Scan your shoulders and upper arms. Compare left to right. Any asymmetry?', duration: 25 },
      { instruction: 'Feel your forearms, wrists, and hands. Hands reflect autonomic state - warm hands = parasympathetic; cool hands = sympathetic.', duration: 30 },
      { instruction: 'Move to your chest. The heart generates significant warmth. Can you sense a warm zone around your heart?', duration: 25 },
      { instruction: 'Feel your abdomen. The digestive organs generate metabolic heat, especially after eating.', duration: 25 },
      { instruction: 'Scan your thighs, knees, calves. Large muscles are usually warm; joints can be cooler.', duration: 25 },
      { instruction: 'Finally, your feet and toes. Like your hands, foot temperature reflects your autonomic balance.', duration: 25 },
      { instruction: 'Now sense your whole body as a thermal landscape. Where are the warmest spots? The coolest? The boundaries between?', duration: 30 },
      { instruction: 'Open your eyes. You have a thermal snapshot. Over time, you will notice how this map changes with stress, relaxation, and exercise.', duration: 15 },
    ],
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id);
}

export function getExercisesByCategory(category: ExerciseCategory): Exercise[] {
  return EXERCISES.filter(e => e.category === category);
}

export function getExercisesByCondition(condition: TargetCondition): Exercise[] {
  return EXERCISES.filter(e => e.targetConditions.includes(condition));
}

export function getExercisesByDifficulty(difficulty: Exercise['difficulty']): Exercise[] {
  return EXERCISES.filter(e => e.difficulty === difficulty);
}
