export interface ExerciseStep {
  instruction: string;
  duration: number;
}

export interface Exercise {
  id: string;
  title: string;
  subtitle: string;
  category: ExerciseCategory;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  durationMinutes: number;
  benefits: string[];
  steps: ExerciseStep[];
  iconName: string;
}

export type ExerciseCategory = 'heartbeat' | 'breathing' | 'bodyScanning' | 'tension' | 'temperature' | 'exposure';

export const CATEGORY_INFO: Record<ExerciseCategory, { label: string; icon: string; description: string }> = {
  heartbeat: { label: 'Heartbeat', icon: 'heart', description: 'Detect and attune to your heartbeat' },
  breathing: { label: 'Breathwork', icon: 'wind', description: 'Master breath awareness and control' },
  bodyScanning: { label: 'Body Scan', icon: 'activity', description: 'Systematically scan your entire body' },
  tension: { label: 'Tension', icon: 'zap', description: 'Locate and release muscular tension' },
  temperature: { label: 'Temperature', icon: 'thermometer', description: 'Notice thermal sensations' },
  exposure: { label: 'Exposure', icon: 'shield', description: 'Build resilience through safe exposure' },
};

export const EXERCISES: Exercise[] = [
  {
    id: 'heartbeat-detection',
    title: 'Heartbeat Detection',
    subtitle: 'Feel your pulse without touching',
    category: 'heartbeat',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Improves cardiac awareness', 'Reduces anxiety', 'Grounds you in the present'],
    iconName: 'heart',
    steps: [
      { instruction: 'Find a comfortable seated position. Close your eyes gently.', duration: 15 },
      { instruction: 'Take three deep breaths to settle in. Let your breathing return to normal.', duration: 20 },
      { instruction: 'Without placing your hand on your chest, try to feel your heartbeat from within.', duration: 30 },
      { instruction: 'Focus your attention on your chest area. Can you sense each beat?', duration: 45 },
      { instruction: 'If you can feel it, count the beats silently. If not, that is perfectly fine.', duration: 45 },
      { instruction: 'Now shift attention to your fingertips. Can you feel a pulse there?', duration: 30 },
      { instruction: 'Move your awareness to your neck. Notice any pulsing sensation.', duration: 30 },
      { instruction: 'Return attention to your chest. Notice if awareness has sharpened.', duration: 45 },
      { instruction: 'Gently open your eyes. Take a moment to reflect on what you noticed.', duration: 20 },
    ],
  },
  {
    id: 'resting-heart-awareness',
    title: 'Resting Heart Awareness',
    subtitle: 'Deep cardiac interoception',
    category: 'heartbeat',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Deepens body connection', 'Calms nervous system', 'Enhances emotional awareness'],
    iconName: 'heart',
    steps: [
      { instruction: 'Lie down comfortably on your back. Let your arms rest by your sides.', duration: 20 },
      { instruction: 'Close your eyes. Begin with five slow, deep breaths.', duration: 30 },
      { instruction: 'Let your breathing settle naturally. Turn your attention inward.', duration: 20 },
      { instruction: 'Focus on the center of your chest. Imagine listening with your whole body.', duration: 40 },
      { instruction: 'Notice any rhythmic sensation, however faint. Stay curious, not forceful.', duration: 60 },
      { instruction: 'If you notice your heartbeat, observe its rhythm. Is it fast? Slow? Steady?', duration: 60 },
      { instruction: 'Now take a slightly deeper breath and hold for 3 seconds. Notice how your heart responds.', duration: 30 },
      { instruction: 'Release the breath slowly. Feel the heartbeat settle.', duration: 30 },
      { instruction: 'Repeat: deeper breath, hold, release. Observe the heart each time.', duration: 60 },
      { instruction: 'Rest in stillness. Simply witness your heart doing its work.', duration: 60 },
      { instruction: 'Slowly bring awareness back to the room. Open your eyes when ready.', duration: 20 },
    ],
  },
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    subtitle: 'Structured 4-4-4-4 breathwork',
    category: 'breathing',
    difficulty: 'beginner',
    durationMinutes: 6,
    benefits: ['Activates parasympathetic system', 'Reduces stress hormones', 'Improves focus'],
    iconName: 'wind',
    steps: [
      { instruction: 'Sit upright with your feet flat on the floor. Relax your shoulders.', duration: 15 },
      { instruction: 'Exhale completely through your mouth, emptying your lungs.', duration: 10 },
      { instruction: 'Inhale slowly through your nose for 4 counts.', duration: 6 },
      { instruction: 'Hold your breath for 4 counts. Stay relaxed.', duration: 6 },
      { instruction: 'Exhale slowly through your mouth for 4 counts.', duration: 6 },
      { instruction: 'Hold empty for 4 counts. Remain calm.', duration: 6 },
      { instruction: 'Inhale through your nose for 4 counts. Feel your chest expand.', duration: 6 },
      { instruction: 'Hold for 4 counts. Notice the fullness.', duration: 6 },
      { instruction: 'Exhale for 4 counts. Release all tension.', duration: 6 },
      { instruction: 'Hold empty for 4 counts. Embrace the stillness.', duration: 6 },
      { instruction: 'Continue this pattern. Inhale 4 counts.', duration: 6 },
      { instruction: 'Hold 4 counts.', duration: 6 },
      { instruction: 'Exhale 4 counts.', duration: 6 },
      { instruction: 'Hold empty 4 counts.', duration: 6 },
      { instruction: 'Two more rounds on your own. Maintain the rhythm.', duration: 50 },
      { instruction: 'Let your breathing return to its natural rhythm. Notice how you feel.', duration: 20 },
    ],
  },
  {
    id: 'diaphragmatic-breathing',
    title: 'Diaphragmatic Breathing',
    subtitle: 'Deep belly breath technique',
    category: 'breathing',
    difficulty: 'beginner',
    durationMinutes: 7,
    benefits: ['Reduces heart rate', 'Lowers blood pressure', 'Promotes deep relaxation'],
    iconName: 'wind',
    steps: [
      { instruction: 'Lie on your back or sit comfortably. Place one hand on your chest, one on your belly.', duration: 15 },
      { instruction: 'Breathe normally. Notice which hand rises more.', duration: 20 },
      { instruction: 'Now inhale slowly through your nose. Direct the breath into your belly.', duration: 10 },
      { instruction: 'Your belly hand should rise while your chest hand stays relatively still.', duration: 10 },
      { instruction: 'Exhale slowly through pursed lips. Feel your belly lower.', duration: 10 },
      { instruction: 'Continue this pattern. Inhale into the belly for 4 counts.', duration: 8 },
      { instruction: 'Exhale slowly for 6 counts. The longer exhale calms your system.', duration: 10 },
      { instruction: 'Keep going. Inhale 4 counts into the belly.', duration: 8 },
      { instruction: 'Exhale 6 counts. Feel the relaxation deepen.', duration: 10 },
      { instruction: 'Continue for several more breaths on your own.', duration: 90 },
      { instruction: 'Notice the quality of calm in your body now. Let it settle.', duration: 30 },
      { instruction: 'Release the technique. Breathe naturally. Observe the difference.', duration: 20 },
    ],
  },
  {
    id: '478-breathing',
    title: '4-7-8 Relaxation Breath',
    subtitle: 'The natural tranquilizer',
    category: 'breathing',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Induces deep calm', 'Helps with sleep', 'Reduces anxiety quickly'],
    iconName: 'wind',
    steps: [
      { instruction: 'Sit comfortably with your back straight. Let your tongue rest behind your upper front teeth.', duration: 15 },
      { instruction: 'Exhale completely through your mouth, making a whoosh sound.', duration: 10 },
      { instruction: 'Close your mouth. Inhale quietly through your nose for 4 counts.', duration: 8 },
      { instruction: 'Hold your breath for 7 counts. Stay relaxed.', duration: 10 },
      { instruction: 'Exhale completely through your mouth with a whoosh for 8 counts.', duration: 12 },
      { instruction: 'That completes one cycle. Inhale again for 4 counts.', duration: 8 },
      { instruction: 'Hold for 7 counts. Notice the stillness within.', duration: 10 },
      { instruction: 'Exhale with whoosh for 8 counts. Feel tension leaving.', duration: 12 },
      { instruction: 'Third cycle. Inhale 4 counts.', duration: 8 },
      { instruction: 'Hold 7 counts. Your body knows what to do.', duration: 10 },
      { instruction: 'Exhale 8 counts. Deeply releasing.', duration: 12 },
      { instruction: 'Fourth cycle. Inhale 4 counts.', duration: 8 },
      { instruction: 'Hold 7 counts. Almost there.', duration: 10 },
      { instruction: 'Exhale 8 counts. Complete release.', duration: 12 },
      { instruction: 'Continue for 3 more rounds at your own pace.', duration: 100 },
      { instruction: 'Return to natural breathing. Notice the profound calm.', duration: 30 },
    ],
  },
  {
    id: 'progressive-body-scan',
    title: 'Progressive Body Scan',
    subtitle: 'Head-to-toe awareness journey',
    category: 'bodyScanning',
    difficulty: 'beginner',
    durationMinutes: 12,
    benefits: ['Reveals hidden tension', 'Improves body literacy', 'Promotes full-body relaxation'],
    iconName: 'activity',
    steps: [
      { instruction: 'Lie down comfortably. Close your eyes. Take three deep breaths.', duration: 20 },
      { instruction: 'Bring your attention to the top of your head. Notice any sensations: tingling, pressure, warmth.', duration: 30 },
      { instruction: 'Move awareness to your forehead and temples. Release any tension you find.', duration: 30 },
      { instruction: 'Notice your eyes, cheeks, and jaw. Let your jaw soften and relax.', duration: 30 },
      { instruction: 'Feel your neck and throat. Swallow once and notice the sensation.', duration: 25 },
      { instruction: 'Scan your shoulders. Are they raised? Let them drop away from your ears.', duration: 30 },
      { instruction: 'Move down through your upper arms, elbows, forearms, and into your hands.', duration: 40 },
      { instruction: 'Feel each finger individually. Notice tingling or warmth in your fingertips.', duration: 30 },
      { instruction: 'Bring attention to your chest. Notice the rise and fall of breathing.', duration: 35 },
      { instruction: 'Scan your upper back and mid-back. Notice any tightness or holding.', duration: 30 },
      { instruction: 'Feel your stomach and lower abdomen. Notice any butterflies or tightness.', duration: 30 },
      { instruction: 'Move to your lower back and hips. Let them settle into the surface beneath you.', duration: 30 },
      { instruction: 'Scan down through your thighs, knees, and calves.', duration: 30 },
      { instruction: 'Feel your ankles, the soles of your feet, and each toe.', duration: 30 },
      { instruction: 'Now expand your awareness to your whole body at once. Feel it as one connected whole.', duration: 45 },
      { instruction: 'Rest in this full-body awareness for a moment.', duration: 30 },
      { instruction: 'Gently wiggle your fingers and toes. Open your eyes slowly.', duration: 15 },
    ],
  },
  {
    id: 'focused-body-scan',
    title: 'Focused Area Scan',
    subtitle: 'Deep dive into one body region',
    category: 'bodyScanning',
    difficulty: 'intermediate',
    durationMinutes: 10,
    benefits: ['Develops precision awareness', 'Identifies subtle signals', 'Releases chronic holding'],
    iconName: 'activity',
    steps: [
      { instruction: 'Sit or lie comfortably. Choose one area of your body that calls your attention.', duration: 20 },
      { instruction: 'Take five deep breaths to center yourself.', duration: 30 },
      { instruction: 'Bring all your attention to your chosen area. What do you notice first?', duration: 30 },
      { instruction: 'Is there warmth or coolness? Tightness or openness? Tingling or numbness?', duration: 40 },
      { instruction: 'Breathe into that area. Imagine your breath flowing directly there.', duration: 40 },
      { instruction: 'Notice the edges of the sensation. Where does it begin and end?', duration: 40 },
      { instruction: 'Does the sensation have a shape? A color? A texture? Stay curious.', duration: 40 },
      { instruction: 'Has the sensation changed since you started? How?', duration: 40 },
      { instruction: 'Send a sense of acceptance to this area. It is simply information.', duration: 40 },
      { instruction: 'Take three more breaths directed to this area.', duration: 25 },
      { instruction: 'Slowly expand your awareness back to your whole body.', duration: 20 },
      { instruction: 'Open your eyes. Reflect on what you discovered.', duration: 15 },
    ],
  },
  {
    id: 'tension-release',
    title: 'Progressive Tension Release',
    subtitle: 'Tense and release muscle groups',
    category: 'tension',
    difficulty: 'beginner',
    durationMinutes: 10,
    benefits: ['Reduces physical stress', 'Teaches tension awareness', 'Improves sleep quality'],
    iconName: 'zap',
    steps: [
      { instruction: 'Lie on your back or sit in a supportive chair. Close your eyes.', duration: 15 },
      { instruction: 'Clench both fists as tight as you can. Hold the tension.', duration: 8 },
      { instruction: 'Release your fists completely. Notice the difference between tension and relaxation.', duration: 15 },
      { instruction: 'Tense your forearms by bending your wrists toward you. Hold.', duration: 8 },
      { instruction: 'Release. Feel the warmth flow into your arms.', duration: 15 },
      { instruction: 'Shrug your shoulders up to your ears. Hold tight.', duration: 8 },
      { instruction: 'Drop them. Feel the weight release.', duration: 15 },
      { instruction: 'Scrunch your face: squeeze eyes, purse lips, wrinkle nose. Hold.', duration: 8 },
      { instruction: 'Let your face soften completely. Feel the smoothness.', duration: 15 },
      { instruction: 'Press your shoulder blades together. Hold the squeeze.', duration: 8 },
      { instruction: 'Release. Notice the expansion across your back.', duration: 15 },
      { instruction: 'Tighten your abs as if bracing for impact. Hold.', duration: 8 },
      { instruction: 'Release. Let your belly be soft and relaxed.', duration: 15 },
      { instruction: 'Squeeze your glutes and thighs. Hold firm.', duration: 8 },
      { instruction: 'Release. Feel heaviness settle into your lower body.', duration: 15 },
      { instruction: 'Point your toes away from you, tensing your calves. Hold.', duration: 8 },
      { instruction: 'Release. Let your feet fall naturally.', duration: 15 },
      { instruction: 'Now tense your entire body at once. Every muscle. Hold.', duration: 10 },
      { instruction: 'Release everything. Melt into total relaxation.', duration: 30 },
      { instruction: 'Rest here. Notice how different your body feels now.', duration: 30 },
    ],
  },
  {
    id: 'jaw-neck-release',
    title: 'Jaw & Neck Release',
    subtitle: 'Target stress storage areas',
    category: 'tension',
    difficulty: 'beginner',
    durationMinutes: 6,
    benefits: ['Relieves headache tension', 'Reduces jaw clenching', 'Eases neck stiffness'],
    iconName: 'zap',
    steps: [
      { instruction: 'Sit upright. Notice where your tongue rests in your mouth right now.', duration: 15 },
      { instruction: 'Let your jaw hang slightly open. Feel the space between your upper and lower teeth.', duration: 15 },
      { instruction: 'Slowly move your jaw side to side. Notice any clicking or tightness.', duration: 20 },
      { instruction: 'Open your mouth wide, then close slowly. Repeat three times.', duration: 20 },
      { instruction: 'Place your fingertips on your jaw joints. Massage in small circles.', duration: 25 },
      { instruction: 'Drop your chin to your chest. Feel the stretch along the back of your neck.', duration: 20 },
      { instruction: 'Slowly roll your head to the right. Pause where you feel tension.', duration: 20 },
      { instruction: 'Roll your head back to center, then to the left. Breathe into tight spots.', duration: 20 },
      { instruction: 'Return to center. Shrug shoulders up, hold 5 seconds, then release.', duration: 15 },
      { instruction: 'Repeat the shrug two more times. Higher each time, then deeper release.', duration: 30 },
      { instruction: 'Sit still. Notice how your jaw and neck feel now compared to when you started.', duration: 20 },
    ],
  },
  {
    id: 'temperature-awareness',
    title: 'Temperature Awareness',
    subtitle: 'Sense warmth and coolness',
    category: 'temperature',
    difficulty: 'beginner',
    durationMinutes: 7,
    benefits: ['Develops thermal sensitivity', 'Enhances interoceptive precision', 'Promotes calm focus'],
    iconName: 'thermometer',
    steps: [
      { instruction: 'Sit comfortably with your hands resting on your thighs. Close your eyes.', duration: 15 },
      { instruction: 'Focus on your hands. Notice their temperature. Are they warm or cool?', duration: 25 },
      { instruction: 'Compare your left hand to your right. Is one warmer than the other?', duration: 25 },
      { instruction: 'Now notice your face. Is your forehead warm or cool? What about your cheeks?', duration: 25 },
      { instruction: 'Focus on the tip of your nose. It is often one of the coolest parts of the body.', duration: 25 },
      { instruction: 'Notice the temperature of the air as you inhale. Cool air entering your nostrils.', duration: 25 },
      { instruction: 'As you exhale, notice the warmer air leaving. Feel the contrast.', duration: 25 },
      { instruction: 'Bring attention to your feet. Are they warm or cold? Can you feel each toe?', duration: 25 },
      { instruction: 'Now scan from head to toe. Create a temperature map of your whole body.', duration: 40 },
      { instruction: 'Notice which areas feel warmest. These often have the most blood flow.', duration: 30 },
      { instruction: 'Which areas feel coolest? These are farther from your core.', duration: 25 },
      { instruction: 'Take a deep breath. Open your eyes. Remember what you noticed.', duration: 15 },
    ],
  },
  {
    id: 'warm-hands',
    title: 'Warm Hands Practice',
    subtitle: 'Direct blood flow with intention',
    category: 'temperature',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Teaches autonomic control', 'Reduces stress response', 'Builds mind-body connection'],
    iconName: 'thermometer',
    steps: [
      { instruction: 'Sit with your hands resting palms-up on your thighs. Close your eyes.', duration: 15 },
      { instruction: 'Notice the current temperature of your hands. Rate it mentally: cold, cool, neutral, warm, hot.', duration: 20 },
      { instruction: 'Take five slow breaths to relax your body.', duration: 30 },
      { instruction: 'Imagine warm sunlight shining directly onto your palms.', duration: 30 },
      { instruction: 'Visualize the warmth spreading from your palms through your fingers.', duration: 40 },
      { instruction: 'With each exhale, imagine breathing warmth into your hands.', duration: 40 },
      { instruction: 'Feel the blood flowing down your arms and pooling warmly in your hands.', duration: 40 },
      { instruction: 'Your hands are growing warmer. Feel the tingling of increased blood flow.', duration: 40 },
      { instruction: 'Continue breathing warmth into your hands. No effort, just gentle intention.', duration: 60 },
      { instruction: 'Notice how your hands feel now compared to when you started.', duration: 20 },
      { instruction: 'This ability to direct blood flow is a powerful interoceptive skill.', duration: 15 },
      { instruction: 'Open your eyes. Carry this awareness with you.', duration: 15 },
    ],
  },
  {
    id: 'breath-counting',
    title: 'Breath Counting',
    subtitle: 'Mindful attention anchor',
    category: 'breathing',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Improves concentration', 'Calms racing thoughts', 'Builds breath awareness'],
    iconName: 'wind',
    steps: [
      { instruction: 'Sit comfortably. Let your breath flow naturally without controlling it.', duration: 15 },
      { instruction: 'On your next exhale, silently count "one."', duration: 10 },
      { instruction: 'Inhale naturally. On the next exhale, count "two."', duration: 10 },
      { instruction: 'Continue counting each exhale up to ten.', duration: 80 },
      { instruction: 'When you reach ten, start back at one.', duration: 10 },
      { instruction: 'If you lose count, simply start again at one. No judgment.', duration: 15 },
      { instruction: 'Continue this practice. Count exhales from one to ten.', duration: 90 },
      { instruction: 'Notice how your breathing may naturally slow down.', duration: 20 },
      { instruction: 'Let go of the counting. Simply observe your breath for a moment.', duration: 20 },
      { instruction: 'Open your eyes when you feel ready.', duration: 10 },
    ],
  },
  {
    id: 'gut-feeling-scan',
    title: 'Gut Feeling Awareness',
    subtitle: 'Listen to your visceral signals',
    category: 'bodyScanning',
    difficulty: 'intermediate',
    durationMinutes: 8,
    benefits: ['Improves gut-brain connection', 'Enhances intuition', 'Reduces digestive stress'],
    iconName: 'activity',
    steps: [
      { instruction: 'Sit or lie comfortably. Place one hand lightly on your lower abdomen.', duration: 15 },
      { instruction: 'Close your eyes. Take five slow breaths, letting your belly expand with each inhale.', duration: 30 },
      { instruction: 'Focus all attention on the area beneath your hand. What do you feel?', duration: 30 },
      { instruction: 'Notice any gurgling, movement, or warmth. Your gut is always active.', duration: 40 },
      { instruction: 'Is there any tightness or knots? This often signals emotional holding.', duration: 30 },
      { instruction: 'Breathe softly into your belly. Imagine the breath soothing this area.', duration: 40 },
      { instruction: 'Think of something that makes you slightly nervous. Notice your gut response.', duration: 30 },
      { instruction: 'Now think of something comforting. How does your gut respond differently?', duration: 30 },
      { instruction: 'Return to neutral awareness. Simply observe without judgment.', duration: 40 },
      { instruction: 'Your gut contains millions of nerve endings. It truly is your "second brain."', duration: 20 },
      { instruction: 'Remove your hand. Maintain the internal awareness. Open your eyes.', duration: 15 },
    ],
  },
  {
    id: 'shoulder-check',
    title: 'Shoulder Stress Check',
    subtitle: 'Release stored emotional tension',
    category: 'tension',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Relieves chronic shoulder tension', 'Reduces stress posture', 'Improves breathing depth'],
    iconName: 'zap',
    steps: [
      { instruction: 'Stand or sit tall. Notice where your shoulders are right now.', duration: 10 },
      { instruction: 'Are they crept up toward your ears? Most people carry tension here unknowingly.', duration: 15 },
      { instruction: 'Inhale and deliberately raise your shoulders as high as possible.', duration: 8 },
      { instruction: 'Hold them there. Feel the tension. This is what chronic stress feels like.', duration: 8 },
      { instruction: 'Exhale and let them drop completely. Ahh.', duration: 10 },
      { instruction: 'Again: inhale, shoulders up. Feel the effort.', duration: 8 },
      { instruction: 'Exhale, let them fall. Notice the relief.', duration: 10 },
      { instruction: 'One more time: inhale, lift. Hold the tension.', duration: 8 },
      { instruction: 'Exhale and release. Let gravity do the work.', duration: 10 },
      { instruction: 'Roll your shoulders backward three times slowly.', duration: 20 },
      { instruction: 'Now forward three times.', duration: 20 },
      { instruction: 'Sit still. Notice how much lower your shoulders sit now. Remember this feeling.', duration: 20 },
    ],
  },
  {
    id: 'cold-exposure-intro',
    title: 'Cold Sensation Intro',
    subtitle: 'Safe introduction to cold stimulus',
    category: 'exposure',
    difficulty: 'beginner',
    durationMinutes: 5,
    benefits: ['Builds distress tolerance', 'Activates vagus nerve', 'Increases resilience'],
    iconName: 'shield',
    steps: [
      { instruction: 'You will need a cup of cold water. Hold it in both hands.', duration: 15 },
      { instruction: 'Notice the temperature against your palms. Rate the coldness 1-10.', duration: 15 },
      { instruction: 'Pay attention to your body reaction. Are you tensing up? Pulling away?', duration: 20 },
      { instruction: 'Breathe slowly. Stay with the sensation. It is not dangerous, just unfamiliar.', duration: 30 },
      { instruction: 'Notice: does the coldness feel less intense now? Your body is adapting.', duration: 25 },
      { instruction: 'Dip one finger into the water. Notice the sharper cold on your fingertip.', duration: 20 },
      { instruction: 'Hold your finger in the water. Breathe through the discomfort.', duration: 20 },
      { instruction: 'Remove your finger. Feel the contrast of air temperature on your wet skin.', duration: 15 },
      { instruction: 'Notice: your body managed the cold without any real distress.', duration: 15 },
      { instruction: 'This is interoceptive exposure: experiencing a sensation and staying present with it.', duration: 15 },
      { instruction: 'Set the cup down. Notice how alert and alive you feel now.', duration: 15 },
    ],
  },
  {
    id: 'breath-hold-exposure',
    title: 'Breath Hold Practice',
    subtitle: 'Safely explore breath hunger',
    category: 'exposure',
    difficulty: 'intermediate',
    durationMinutes: 7,
    benefits: ['Reduces panic sensitivity', 'Builds CO2 tolerance', 'Develops emotional regulation'],
    iconName: 'shield',
    steps: [
      { instruction: 'Sit comfortably. This exercise involves brief, safe breath holds.', duration: 15 },
      { instruction: 'Take five normal breaths to establish your baseline.', duration: 25 },
      { instruction: 'After your next exhale, close your mouth and pinch your nose gently.', duration: 10 },
      { instruction: 'Hold for just 5 seconds. Notice the initial urge to breathe.', duration: 8 },
      { instruction: 'Release and breathe normally. That urge is CO2 signaling, not danger.', duration: 20 },
      { instruction: 'Take a few recovery breaths. Notice your heart rate.', duration: 20 },
      { instruction: 'Try again: exhale, hold for 10 seconds this time.', duration: 15 },
      { instruction: 'Release and breathe. Notice the relief. Your body managed it perfectly.', duration: 20 },
      { instruction: 'Recovery breaths. Notice how quickly your body returns to baseline.', duration: 25 },
      { instruction: 'One more: exhale, hold for 15 seconds. Stay calm and present.', duration: 20 },
      { instruction: 'Release. Breathe normally. You just proved to your body it can handle discomfort.', duration: 20 },
      { instruction: 'Take a minute of normal breathing. Reflect on what you noticed.', duration: 40 },
      { instruction: 'This practice helps reduce the fear of uncomfortable body sensations.', duration: 15 },
    ],
  },
  {
    id: 'loving-kindness-body',
    title: 'Body Gratitude Scan',
    subtitle: 'Send compassion to each body part',
    category: 'bodyScanning',
    difficulty: 'beginner',
    durationMinutes: 10,
    benefits: ['Improves body image', 'Reduces self-criticism', 'Deepens body appreciation'],
    iconName: 'activity',
    steps: [
      { instruction: 'Sit or lie comfortably. Close your eyes and take three settling breaths.', duration: 20 },
      { instruction: 'Bring attention to your feet. Thank them silently for carrying you today.', duration: 30 },
      { instruction: 'Move to your legs. Appreciate their strength and ability to move you through the world.', duration: 30 },
      { instruction: 'Focus on your hips and pelvis. The foundation of your body. Send them gratitude.', duration: 30 },
      { instruction: 'Notice your abdomen. It processes nourishment for you every day. Thank it.', duration: 30 },
      { instruction: 'Feel your chest and lungs. They breathe for you without being asked. Appreciate this.', duration: 30 },
      { instruction: 'Your heart has been beating since before you were born. Send it deep gratitude.', duration: 30 },
      { instruction: 'Notice your arms and hands. They create, hold, and connect you to others. Thank them.', duration: 30 },
      { instruction: 'Feel your shoulders, neck, and throat. They carry so much. Send them compassion.', duration: 30 },
      { instruction: 'Your face expresses your inner world. Soften it with kindness.', duration: 25 },
      { instruction: 'Your brain orchestrates everything. Thank it for its tireless work.', duration: 25 },
      { instruction: 'Expand awareness to your whole body. Say silently: "Thank you, body, for being home."', duration: 30 },
      { instruction: 'Rest in this feeling of wholeness and gratitude. Open your eyes when ready.', duration: 20 },
    ],
  },
  {
    id: 'peripheral-awareness',
    title: 'Peripheral Awareness',
    subtitle: 'Expand your sensory field',
    category: 'exposure',
    difficulty: 'advanced',
    durationMinutes: 10,
    benefits: ['Expands body awareness range', 'Reduces tunnel vision anxiety', 'Develops panoramic sensing'],
    iconName: 'shield',
    steps: [
      { instruction: 'Sit comfortably with your eyes open. Fix your gaze softly on a point ahead.', duration: 15 },
      { instruction: 'Without moving your eyes, become aware of what is in your peripheral vision.', duration: 25 },
      { instruction: 'Now close your eyes. Can you sense the space around your body?', duration: 25 },
      { instruction: 'Focus on your skin. Can you feel the air touching it? The clothes on your body?', duration: 30 },
      { instruction: 'Expand your hearing. What is the most distant sound you can detect?', duration: 30 },
      { instruction: 'What is the closest, most subtle sound? Perhaps your own breathing.', duration: 25 },
      { instruction: 'Now try to be aware of all your senses simultaneously. Sight, sound, touch, smell.', duration: 40 },
      { instruction: 'Add internal awareness: heartbeat, breathing, temperature, gut sensations.', duration: 40 },
      { instruction: 'Hold this expanded awareness. You are sensing both inside and outside your body.', duration: 45 },
      { instruction: 'This panoramic awareness is the essence of advanced interoception.', duration: 20 },
      { instruction: 'Slowly narrow your focus back to just your breath. Then open your eyes.', duration: 25 },
    ],
  },
  {
    id: 'emotion-body-mapping',
    title: 'Emotion Body Mapping',
    subtitle: 'Where emotions live in your body',
    category: 'bodyScanning',
    difficulty: 'advanced',
    durationMinutes: 12,
    benefits: ['Links emotions to sensations', 'Develops emotional intelligence', 'Enables earlier emotional detection'],
    iconName: 'activity',
    steps: [
      { instruction: 'Sit comfortably. Close your eyes. Take five deep breaths.', duration: 30 },
      { instruction: 'Do a quick baseline scan of your body. Notice what is present right now.', duration: 30 },
      { instruction: 'Now recall a moment of genuine happiness. Let the memory be vivid.', duration: 20 },
      { instruction: 'Where in your body do you feel happiness? Chest? Face? Stomach? Note the location.', duration: 40 },
      { instruction: 'What is the quality of the sensation? Warmth? Expansion? Lightness?', duration: 30 },
      { instruction: 'Let the memory fade. Return to neutral with three breaths.', duration: 20 },
      { instruction: 'Now recall a moment of mild anxiety or nervousness.', duration: 15 },
      { instruction: 'Where does anxiety show up in your body? Throat? Chest? Stomach? Hands?', duration: 40 },
      { instruction: 'What does it feel like? Tightness? Butterflies? Heat? Tingling?', duration: 30 },
      { instruction: 'Let it go. Three recovery breaths back to neutral.', duration: 20 },
      { instruction: 'Recall a moment of sadness. Where does sadness live in your body?', duration: 30 },
      { instruction: 'Notice: heavy chest? Throat tightness? Pressure behind the eyes?', duration: 30 },
      { instruction: 'Release. Three breaths to neutral.', duration: 20 },
      { instruction: 'Finally, recall a moment of calm confidence. Where is it in your body?', duration: 30 },
      { instruction: 'Remember: your body always knows how you feel, sometimes before your mind does.', duration: 20 },
      { instruction: 'Open your eyes. You now have a personal map of how emotions feel in your body.', duration: 20 },
    ],
  },
  {
    id: 'micro-movement-scan',
    title: 'Micro-Movement Detection',
    subtitle: 'Sense the subtlest body motions',
    category: 'tension',
    difficulty: 'advanced',
    durationMinutes: 8,
    benefits: ['Ultra-fine body awareness', 'Detects unconscious tension', 'Reveals stress patterns'],
    iconName: 'zap',
    steps: [
      { instruction: 'Sit completely still. Close your eyes. Set an intention to be utterly still.', duration: 15 },
      { instruction: 'You will notice that even in stillness, your body moves. Begin to detect these movements.', duration: 25 },
      { instruction: 'Your chest rises and falls with breath. Notice this movement without changing it.', duration: 30 },
      { instruction: 'Can you detect your pulse anywhere? A subtle rhythmic movement?', duration: 35 },
      { instruction: 'Notice any involuntary muscle twitches. Perhaps in your eyelids, fingers, or legs.', duration: 35 },
      { instruction: 'Is your body swaying slightly? Even seated, we gently rock.', duration: 30 },
      { instruction: 'Are you unconsciously clenching anything? Jaw? Fists? Toes? Release them.', duration: 30 },
      { instruction: 'Notice swallowing. It happens automatically every minute or so.', duration: 25 },
      { instruction: 'Listen for any stomach sounds or movements. Digestion is constant subtle motion.', duration: 30 },
      { instruction: 'Your body is never truly still. It is a symphony of micro-movements.', duration: 20 },
      { instruction: 'This awareness of subtle body signals is the core of interoception.', duration: 15 },
      { instruction: 'Open your eyes. Carry this refined awareness into your day.', duration: 15 },
    ],
  },
];

export function getExercisesByCategory(category: ExerciseCategory): Exercise[] {
  return EXERCISES.filter(e => e.category === category);
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find(e => e.id === id);
}
